  # Site settings
title: Open Buddha
description: 'Open Source Buddhism, Technology, and Geekery'
url: 'http://www.openbuddha.com'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Albert Billings'
  email: albill@gmail.com
  twitter_username: makehacklearn
  facebook_username: albill
  github_username:  albill
  linkedin_username:  albill

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink:  /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
