# Site settings
title: Open Buddha
tagline: 'Open Source Buddhism, Technology, and Geekery'
description: 'Open Source Buddhism, Technology, and Geekery'
url: 'http://www.openbuddha.com'
baseurl:             ''
paginate:            5
permalink:  /:year/:month/:day/:title/

# About/contact
author:
  name:              Albert Billings
  url:               https://twitter.com/makehacklearn
  email:             albill@gmail.com

# Custom vars
version:             1.0.0


