title: Open Buddha
tagline: 
description: 'Open Source Buddhism, Technology, and Geekery'
location: "The Bay Area, California"

# Setup
baseurl:             ''
paginate:            5
url: "http://www.openbuddha.com" # replace by your site's url

# About/contact
author:
  name:              Albert Billings
  url:               https://twitter.com/makehacklearn
  email:             albill@gmail.com

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# exclude files
exclude:
  - LICENSE
  - README.md

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Custom vars
version:             1.0.0
