# Site Info
title:              "Open Buddha"
description:        "Open Source Buddhism, Technology, and Geekery"
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code

# Author Info
author_name:        "Albert Billings" # Your name here
author_email:       albill@gmail.com # Your email here
author_gravatar:    ef672fa746dc62198600f30c2469bc27 # Your Gravatar md5 hash here for logo
twitter_username:   loremgibson # Your Twitter username here
github_username:    albill # Your GitHub username here

# Site Settings
url:                https://openbuddha.com # main url
baseurl:            # for gh-pages
permalink:          /:year/:month/:day/:title/ # Post permalink
timezone:           America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
    style:          :compressed

# Other Params

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap
