# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Open Buddha'
tagline:             'Open Source Buddhism, Technology, and Geekery'
description:         'A bunch of stuff goes here'
url:                 http://www.openbuddha.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Al Billings
  url:               https://twitter.com/makehacklearn
  email:             albill@gmail.com

# Custom vars
version:             1.0.0

# exclude files
exclude:
  - LICENSE
  - README.md
