title: "Open Buddha"
description: "Open Source Buddhism, Technology, and Geekery"
about: "Open Source Buddhism, Technology, and Geekery"
location: "The Bay Area, California"
email: somewhere@something.com
baseurl: ""
permalink:  /:year/:month/:day/:title/
paginate: 3

url: "http://www.openbuddha.com" # replace by your site's url
twitter_username: makehacklearn
github_username:  albill
author: "Albert Billings"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

sass:
  sass_dir: css
  style:    expanded
safe: true
lsi: false

# exclude files
exclude:
  - LICENSE
  - README.md
