markdown: rdiscount
server: false
pygments: true
permalink:  /:year/:month/:day/:title/
paginate: 3
url: http://www.openbuddha.com
embedly:
  api_key: ba540e48da1511e0801e4040d3dc5c07
disqus_username: albill
twitter_name: openbuddha
facebook_uid: 139700605
