--- 
wordpress_id: 958
layout: post
title: One of the Coolest Uses of the Net
date: 2002-09-23 01:51:00
wordpress_url: http://www.arcanology.com/?p=958
---
I first heard about this last year but it seems like it is finally happening. One of the best things that I can see on the net for people that simply want to educate themselves, regardless of paper certificates. <a href="http://news.bbc.co.uk/1/hi/technology/2270648.stm">http://news.bbc.co.uk/1/hi/technology/2270648.stm</a> Sunday, 22 September, 2002, 07:16 GMT 08:16 UK <strong>Learn for free online</strong> People will soon be given access to knowledge from one of the world's foremost technology institutes for free over the internet, as BBC World ClickOnline's Ian Hardy reports. Like almost every organisation in the US, the Massachusetts Institute of Technology spent the late 1990s struggling with the question of how to take advantage of the internet. Many other colleges launched online degree courses aimed at anyone with a modem and a big wallet. But MIT has taken a completely different direction with a project called OpenCourseWare (OCW) that could stop the trend of commercialising online education dead in its tracks. The first group of courses are set to be published on the internet on 30 September, including subjects like anthropology, biology, chemistry and computer science. <strong>Education revolution</strong> "I genuinely think there was an 'a-ha' moment when they said our mission was actually to enhance education," said Anne Margulies, Executive Director of OCW. <hr />
        "Our hope and aspiration is that by setting an example, other universities will also put their valued materials on the internet "
        <hr />
        
        <em>Professor Dick Yue, MIT</em>"Why don't we, instead of trying to sell our knowledge over the internet, just give it away." Over the next 10 years, MIT will move all its existing coursework on to the internet. There will be no online degrees for sale, however. Instead, it will offer thousands of pages of information, available to anyone around the globe at no cost, as well as hours and hours of streaming video lectures, seminars and experiments. This is just the tip of the iceberg. MIT wants to start nothing short of a global revolution in education. "Our hope and aspiration is that by setting an example, other universities will also put their valued materials on the internet and thereby make a truly profound and fundamental impact on learning and education worldwide," said MIT's Professor Dick Yue. MIT admits that getting OpenCourseWare ready for its internet debut has been a huge challenge. Staff have spent months clearing up complex copyright issues and designing software tools that will enable hundreds of faculty members to upload their daily lecture notes and video clips directly onto the website. <strong>Free for all</strong> At a time when many internet administrators in America have been removing any technological resources that could be of use to terrorists, MIT will not be sifting online information. <hr />
        " There is no revenue objective for OCW, ever. It will always be free "
        <hr />
        
        <em>Anne Margulies, OCW</em>"With regard to censoring or filtering what might be construed as sensitive materials, at this time we are not doing any of that kind of censorship," said Laura Koller, OCW Project Manager. "As we go forward through our pilot project those issues will certainly come up again and be revisited by faculty, administrators and so forth. But at this time we're publishing all the materials we get." Most websites now have abandoned the idea of offering totally free content. The trick is to lure you to the site with good intentions, then start entangling you in charges. MIT are offering an eternal promise, rare these days on the world wide web. "There is no revenue objective for OCW, ever. It will always be free," insisted Ms Margulies. MIT staff point out that if this initiative is successful, and other institutions follow, it will put the net back on track towards its original goal of sharing information and knowledge around the world, rather than selling CDs and t-shirts.