--- 
layout: post
title: "Neighborhood Hazard (or: Why the Cops Won\xE2\x80\x99t Patrol Brice Street)"
published: true
meta: 
  ljID: "2983"
tags: 
- Daily Life
type: post
status: publish
---
Quoted in entirety from <a href="http://cuagain.manilasites.com/discuss/msgReader%24287?mode=day">here</a>. This was so funny that I had to share:

<blockquote>I never dreamed slowly cruising through a residential neighborhood could be so incredibly dangerous!

Studies have shown that motorcycling requires more decisions per second, and more sheer data processing than nearly any other common activity or sport. The reactions and accurate decision making abilities needed have been likened to the reactions of fighter pilots! The consequences of bad decisions or poor situational awareness are pretty much the same for both groups too.
<p>Occasionally, as a rider I have caught myself starting to make bad or late decisions while riding. In flight training, my instructors called this being “behind the power curve”. It is a mark of experience that when this begins to happen, the rider recognizes the situation, and more importantly, does something about it. A short break, a meal, or even a gas stop can set things right again as it gives the brain achance to catch up. 
</p> <p>Good, accurate, and timely decisions are essential when riding a motorcycle…at least if you want to remain among the living. In short,
the brain needs to keep up with the machine. I had been banging around the roads of east Texas and as I headed back into Dallas, found myself in very heavy, high-speed traffic on the freeways. Normally, this is not a problem, I commute in these conditions daily, but suddenly I was nearly run down by a cage that decided it needed my lane more than I did. This is not normally a big deal either, as it happens around here often, but usually I can accurately predict which drivers are not paying attention and avoid them before we are even close. This one I missed seeing until it was nearly too late, and as I took evasive action I nearly broadsided another car that I was not even aware was there!
</p> <p>Two bad decisions and insufficient situational awareness…all within seconds. I was behind the power curve. Time to get off the freeway.&nbsp; I hit the next exit, and as I was in an area I knew pretty well, headed through a few big residential neighborhoods as a new route home. As I turned onto the nearly empty streets I opened the visor on my full-face helmet to help get some air. I figured some slow riding through the quiet surface streets would give me time to relax, think, and regain that “edge” so frequently required when riding.
</p> <p><i>Little did I suspect…
</i></p> <p>As I passed an oncoming car, a brown furry missile shot out from under it and tumbled to a stop immediately in front of me. It was a squirrel, and must have been trying to run across the road when it encountered the car. I really was not going very fast, but there was no time to brake or avoid it—it was that close. I hate to run over animals…and I really hate it on a motorcycle, but a squirrel should pose no danger to me. I barely had time to brace for the impact.
</p> <p>Animal lovers, never fear. Squirrels can take care of themselves! Inches before impact, the squirrel flipped to his feet. He was standing on his hind legs and facing the oncoming Valkyrie with steadfast resolve in his little beady eyes. His mouth opened, and at the last possible second, he screamed and leapt! I am pretty sure the scream was squirrel for, “Banzai!” or maybe, “Die you gravy-sucking, heathen scum!” as the leap was spectacular and he flew over the windshield and impacted me squarely in the chest.
</p> <p>Instantly he set upon me. If I did not know better I would have sworn he brought twenty of his little buddies along for the attack. Snarling, hissing, and tearing at my clothes, he was a frenzy of activity. As I was dressed only in a light t-shirt, summer riding gloves, and jeans this was a bit of a cause for concern. This furry little tornado was doing some damage! 
</p> <p>Picture a large man on a huge black and chrome cruiser, dressed in jeans, a t-shirt, and leather gloves puttering maybe 25mph down a quiet residential street…and in the fight of his life with a squirrel. <i>And losing.
</i></p> <p>I grabbed for him with my left hand and managed to snag his tail. With all my strength I flung the evil rodent off the left of the bike, almost running into the right curb as I recoiled from the throw. That should have done it. The matter should have ended right there. It really should have. The squirrel could have sailed into one of the pristinely kept yards and gone on about his business, and I could have headed home. No one would have been the wiser.
</p>  <p>But this was no ordinary squirrel. This was not even an ordinary pissed-off squirrel. This was an evil attack squirrel of death!
</p> <p>Somehow he caught my gloved finger with one of his little hands, and with the force of the throw swung around and with a resounding thump and an amazing impact he landed square on my back and resumed his rather anti-social and extremely distracting activities. He also managed to take my left glove with him! 
</p> <p>The situation was not improved. Not improved at all. His attacks were continuing, and now I could not reach him. 
</p> <p>I was startled to say the least. The combination of the force of the throw, only having one hand (the throttle hand) on the handlebars, and my jerking back unfortunately put a healthy twist through my right hand and into the throttle. A healthy twist on the throttle of a Valkyrie can only have one result. Torque. This is what the Valkyrie is made for, and she is <i>very</i>, very good at it. The engine roared as the front wheel left the pavement. The squirrel screamed in anger. The Valkyrie screamed in ecstasy. I screamed in…well…I just plain screamed. 
</p> <p>Now picture a large man on a huge black and chrome cruiser, dressed in jeans, a slightly squirrel torn t-shirt, and only one leather glove roaring at maybe 70mph and rapidly accelerating down a quiet residential street…on one wheel and with a demonic squirrel on his back. The man and the squirrel are both screaming bloody murder. With the sudden acceleration I was forced to put my other hand back on the handlebars and try to get control of the bike. This was leaving the mutant squirrel to his own devices, but I really did not want to crash into somebody’s tree, house, or parked car. Also, I had not yet figured out how to release the throttle…my brain was just simply overloaded. I did manage to mash the back brake, but it had little affect against the massive power of the big cruiser.
</p>   <p>About this time the squirrel decided that I was not paying sufficient attention to this very serious battle (maybe he is a Scottish attack squirrel of death), and he came around my neck and got IN my full-face helmet with me. As the faceplate closed partway and he began hissing in my face I am quite sure my screaming changed tone and intensity. It seemed to have little affect on the squirrel however. 
</p>  <p>The rpm’s on <i>The Dragon</i> maxed out (I was not concerned about shifting at the moment) and her front end started to drop. 
</p> <p>Now picture the large man on the huge black and chrome cruiser, dressed in jeans, a very ragged torn t-shirt, and wearing one leather glove, roaring at probably 80mph, still on one wheel, with a large puffy squirrel’s tail sticking out his mostly closed full-face helmet. By now the screams are probably getting a little hoarse. Finally I got the upper hand…I managed to grab his tail again, pulled him out of my helmet, and slung him to the left as hard as I could. This time it worked…sort-of. Spectacularly sort-of, so to speak. Picture the scene. You are a cop. You and your partner have pulled off on a quiet residential street and parked with your windows down to do some paperwork.
</p> <p>Suddenly a large man on a huge black and chrome cruiser, dressed in jeans, a torn t-shirt flapping in the breeze, and wearing one leather glove, moving at probably 80mph on one wheel, and screaming bloody murder roars by and with all his strength throws a live squirrel grenade directly into your police car.
</p> <p>I heard screams. They weren&apos;t mine...
</p> <p>I managed to get the big motorcycle under directional control and dropped the front wheel to the ground. I then used maximum braking and skidded to a stop in a cloud of tire smoke at the stop sign at a busy cross street.
</p> <p>I would have returned to fess up (and to get my glove back). I really would have. Really. But for two things. First, the cops did not seem interested or the slightest bit concerned about me at the moment. One of them was on his back in the front yard of the house they had been parked in front of and was rapidly crabbing backwards away from the patrol car. The other was standing in the street and was training a riot shotgun on the police cruiser. 
</p> <p>So the cops were not interested in me. They often insist to “let the professionals handle it” anyway. That was one thing. The other? Well, I swear I could see the squirrel, standing in the back window of the patrol car among shredded and flying pieces of foam and upholstery, and shaking his little fist at me. I think he was shooting me the finger…
</p> <p>That is one dangerous squirrel. <i>And now he has a patrol car…
</i></p> <p>I took a deep breath, turned on my turn-signal, made an easy right turn, and sedately left the neighborhood. 
</p> <p>As for my easy and slow drive home? Screw it. Faced with a choice of 80mph cars and inattentive drivers, or the evil, demonic, attack squirrel of death...I’ll take my chances with the freeway. Every time. 
</p> <p>And I’ll buy myself a new pair of gloves.
</p> <p>CUAgain,
Daniel Meyer</p></blockquote>
