--- 
wordpress_id: 2069
layout: post
title: Iamblichus and Dreams
date: 2003-12-14 12:38:00
wordpress_url: http://www.arcanology.com/2003/12/14/iamblichus-and-dreams/
---
<b>IAMBLICHEAN DREAM THEORY </b><br /> <i>John F. Finamore, University of Iowa </i> <p>
                                                                                                                                                                                                                                                                                                                                                        Robert Berchman in an earlier paper in this collection has discussed the dream theory of Philo. Berchman traces the history of the interpretation of dreams from the early Greek poets to Plato, Aristotle, and the Stoics, and shows how Philo in his <i>de Somniis </i>made use of this tradition in his own middle-Platonic dream theory. I intend to examine how dream theory has evolved in the later neoplatonic tradition as evidenced in the <i>de Mysteriis</i> of Iamblichus. Iamblichus borrows from the same tradition as Philo but, because of his expansive metaphysical hierarchy, makes more distinctions about the kinds of dreams termed <i>theopemptoi </i>(god-sent). Nonetheless, the heart of Iamblichean dream theory is remarkably similar to Philo&apos;s, suggesting a relatively smooth tradition of exegesis between the first and fourth centuries C.E.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        Iamblichus, like all Platonists, had to come to grips with what Plato had said about dreams. Plato left the path open to belief in divination through dreams. In the <i>Republic</i> 571c3-572b9, he discusses the effect the rational soul can have on dreams. If the rational soul is asleep, dreams aroused by our lower natures result, dreams of incest, bestiality, murder, etc. If however the rational soul has control over the lower parts, even in sleep it can carry on its thinking and planning unimpeded. It grasps truth and is without unlawful visions. Plato considers the topic twice in the <i>Timaeus</i>. At 45d3-46a2, Plato says that dreams are images (<i>phantasmata</i>) internal to the body. At 71 e2-72b5, Plato takes up the topic of divination in dreams, which he considers possible when the power of thought (<i>phronesis</i>) is shackled in sleep. Dreamers cannot understand these prophetic dreams while they are having them (because their rational souls are overcome), but they or a diviner can interpret the dreams after they have awakened. It would seem, then, that Platonic interpreters who wished to argue that dreams provide true visions could argue either or both of two positions: that dreams impart truth either when the rational soul is alert and controlling the images or when the rational soul is subdued and the images are received without its awareness. Platonic interpreters could also take heart from the fact that Socrates had divinely inspired dreams of his own that he interpreted himself. In <i>Crito</i> 44a10-b2 Socrates dreams that a woman dressed in white tells him the day of his death; in <i>Phaedo</i> 60e4-61b7 Socrates interprets a dream that causes him to take up the writing of poetry.
                                                                                                                                                                                                                                                                                                                                                      </p><lj-cut text="Read the rest."> 
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        Berchman (in section 11.2) has shown that Philo divided dreams into various categories. A major division of types of dreams is into those that are <i>theopemptoi</i>, true, and divinatory and those that arise from the soul itself and fill the sleeper&apos;s faculty of discursive reason (<i>dianoia</i>) with false images and unreliable images (<i>Somn.</i>2.162). Iamblichus in <i>Myst.</i> 3.2<sup><font size=2>1</font></sup> makes the same division into dreams that are <i>theopemptoi</i> and those that are not. This is not surprising since such a division represents an attempt to combine Plato&apos;s own statements about dreams in the <i>Republic</i> and the <i>Timaeus</i>. Human dreams that are not god-sent (<i>anthropinoi oneiroi</i>), Iamblichus says, come from the soul itself (103.2-4), just as the <i>Republic</i> would have it. They are set in motion either by our own thoughts and reasonings or by our daily cares and whatever our phantasiai have aroused (103.4-6).<sup><font size=2>2</font></sup> This disjunction recalls Plato&apos;s distinction in the <i>Republic</i> between the rational soul (<i>logistikon</i>, 571c4 and d7) and the irrational. When we sleep with our rational soul alert and in control, Plato tells us, we are most likely to grasp the truth (572a7-b1). Thus, Iamblichus says that these sorts of dreams may be true or false and sometimes chance upon reality but often do not (103.6-8).
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        Iamblichus, like Philo, accepts different kinds of god-sent dreams. Plato&apos;s writings here presented a difficulty, for in the <i>Timaeus</i> Plato accepted divinatory dreams only when the rational principle is shackled in sleep or when the person is under some form of enthusiasm (<i>Tim.</i> 71e2-6). Both Philo (<i>Somn.</i> 2.1) and Iamblichus,<sup><font size=2>3</font></sup> however, count enthusiasm as only one form (the lowest) of <i>theopemptoi oneiroi</i>, for they both see the higher forms of divination in dreams as occurring when the dreamer&apos;s intellect (<i>nous</i>) is fully aware of what is occurring (<i>Somn.</i> 1.1 and <i>Myst.</i> 3.2, 104.10-12). Their claim is possible, I suspect, not only because Socrates had divine dreams of which he was fully aware (as was mentioned earlier) but also because the passage in the <i>Republic</i> had claimed that the soul could see truths when the rational principle was alert (<i>Rep</i>. 572a7-b1). Iamblichus seems to augment Plato&apos;s words in the needed way in the beginning of <i>de Myst.</i> 3.3, when he argues that it is easier to free our souls from the body when we are asleep:
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <blockquote>
                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                          When awake, we often make use of the life in common with the body, unless we free ourselves from it completely by pure reasoning in intellection and thought. In sleep, we free ourselves completely [from the body] as though from chains attached to us, and we make use of a life separated from generation.<sup><font size=2>4</font></sup> [106.6-9].
                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                      </blockquote>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        The echoes of the <i>Republic</i> are clear enough. Plato had emphasized that the person who has trained reason to command the irrational impulses in the day is the one who controls those impulses and keeps them from interfering with dreams at night. Iamblichus takes the argument one step further and says that the same person who can do this can be fully conscious of <i>theopemptoi</i> dreams.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        Indeed Iamblichus is willing to blur the distinctions of waking and sleeping for <i>theopemptoi</i> dreams. He says that such dreams occur at any of several ideal times: when sleep is slipping away, when we are just beginning to wake, when we are between sleeping and waking,. and even when we are fully awake (103.8-14).<sup><font size=2>5</font></sup> The emphasis on the half-awake or fully awake state indicates a nod in Plato&apos;s direction. We need some degree of alertness to be rational. But how does one "dream" when awake?
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        Iamblichus&apos; answer implies that <i>theopemptoi</i> dreams involve some sort of trance. These dreams must, by definition, be sent by the gods. Since the gods cannot themselves descend into our realm,<sup><font size=2>6</font></sup> Iamblichus tells us that they send either an invisible and incorporeal pneuma (103.15) or a bright and peaceful light (104.4-5). In either case, the dreamer is aware of the pneuma or light (although there are different degrees of awareness, as we shall see) and receives a true, divinatory dream. The dreamer is therefore taken over by the gods. As Iamblichus states in <i>Myst.</i> 3.23, the cause of the mantic dream is not from us (155.8).<sup><font size=2>7</font></sup> Its truth is not of our doing, but the truth illuminates us from itself (155.16-18). The divination therefore "is from the outside (<i>exothen)</i><sup><font size=2>8</font></sup> from the gods and it of its own power, when it wishes and how it wishes, reveals with good will what will be" (155.18-156.3). These <i>theopemptoi</i> dreams, then, are caused by external factors that set up some sort of trance in the dreamer, whether the dreamer is awake or asleep.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        What Iamblichus has in mind is further described in <i>Myst.</i> 3.14, a chapter on the functioning of enthusiasm. In this type of divination divine light is showered upon the soul&apos;s ethereal vehicle.<sup><font size=2>9</font></sup> "Thereupon, divine images take hold of the imaginative power in us" (132.13-14).<sup><font size=2>10</font></sup> The effect of this is to allow the subject to be conscious of what is occurring, because the rational soul is not affected by the divine light, but to allow the gods to control the images that the subject "sees" (133.3-8). Thus, to return to dreams, the dreamer does not control the images in the psychic vehicle; the gods do. But the more alert the rational soul is, the greater awareness the dreamer has of the dream.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        Thus, both Philo and Iamblichus divide dreams into those that are <i>theopemptoi</i> and those that arise from within the dreamer&apos;s soul. Both also discern different classes of <i>theopemptoi</i> dreams. Philo divides these dreams into three kinds.<sup><font size=2>11</font></sup> Philo&apos;s classification is based on three factors: the source of the dream, the level of psyche used by the dreamer, and the degree of clarity of the divination received. Dreams of the first type are sent by god (<i>to theion</i> in <i>Somn.</i> 1.1 and <i>theos</i> in 2.2), are immediately clear (2.2-3), and hence are sent to those like Isaac who preserve the good in themselves and apportion it to their <i>logismos</i> (2.9-10). The second division of <i>theopemptoi</i> dreams is from the soul of the universe (1.2 and 2.2), involves the human intellect and is less clear (1.2, cf. 2.2). The third type originates in the soul of the dreamer (2.1) but is a form of enthusiasm (<i>enthousiosa</i>, 2.1) and so is similar to Iamblichus&apos; conception of enthusiastic dream in which the dreamer is unaware of what is occurring. Hence, the dream is unclear, involves a "deep and profound riddle" (<i>to bathu kai katakores echein to ainigma</i>), and requires interpretive skill (2.4).
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        Iamblichus divides <i>theopemptoi</i> dreams into more classifications than Philo does. The more intricate metaphysical universe of Iamblichean neoplatonism requires a greater variety of dreams.<sup><font size=2>12</font></sup> The sources of the dreams may be the superior classes (angels, heroes, demons, purified souls, etc.), the visible gods, the intellectual gods, the intelligible gods, or the One itself. The soul of the dreamer may be involved with only its irrational nature, with its rational nature, or with its intellect. The clarity of the divination would necessarily differ both with the source and the level of psychic involvement. Nevertheless, there are certain important features of similarity between Philo&apos;s and Iamblichus&apos; systems.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        We have already seen indications of a kind of enthusiasm similar to Philo&apos;s third class of dream in Iamblichus&apos; <i>Myst.</i> 3.14. Further evidence is provided in chapter 3.24, where Iamblichus is again discussing divination. He considers a kind of divination in which the senses are taken over but not by human images (157.8-11), in which the invocations used at the rite of divination awaken neither the inspiration<sup><font size=2>13</font></sup> of the <i>dianoia</i> nor the corporeal passions in the recipient (157.13-14), and in which those who are simpler and young are better suited to receiving the descending pneuma that will produce the divination (157.16-20). Here we clearly have a recipient whose rational soul is intended to be undeveloped so that it will not interfere with the divine images received by the soul&apos;s vehicle. Such a recipient will not be alert to the meaning of the divination but will act merely as a receptacle for the divination, which will be interpreted by others.<sup><font size=2>14</font></sup>
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        Iamblichus in <i>Myst.</i> 3.2 displays one way in which he increases the types of <i>theopemptoi</i> dreams. At 104.4-12 he delineates two types that are differentiated only by the level of psychic involvement of the dreamer.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <blockquote>
                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                          Sometimes when a bright and peaceful light is shining, the vision of the eyes is checked and shut off, although it was in force before. The other senses are alert and perceive how the gods are revealed in the light, hear what they say, and (by attending closely) know what they are doing. A still more perfect [type of divination] is seen when the vision sees, when the intellect, having been strengthened, follows the activities, and when the spectators become involved in the contemplation.
                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                      </blockquote>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        Here Iamblichus first describes (lines 4-9) a dream state intermediary between Philo&apos;s second and third type of dream. Unlike the third type, the dreamer is aware of the god&apos;s presence, words, and actions; unlike the second type, the dreamer&apos;s senses (rather than intellect) are involved. Iamblichus then describes (lines 10-12) a dream state similar to Philo&apos;s second type of dream, in which not only the senses (including vision this time) but also the intellect have become involved.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        In the passage just discussed Iamblichus does not mention the divinity to which the dreamer becomes attached. From elsewhere in the <i>de Mysteriis</i> it is clear (as one would expect) that the higher the divinity, the purer and more clear the divination received.<sup><font size=2>15</font></sup> Iamblichus sheds further light on this issue in <i>Myst.</i> 3.3, a chapter which presents a hierarchy of five types of divination based upon the source of the divination and the level of psychic involvement. This is not a complete account of all possible <i>theopemptoi</i> dreams, nor does Iamblichus intend it as such. At the lower end of the scale, for example, it leaves out enthusiasm-type dreams and begins instead with dreams in which the dreamer&apos;s intellect is engaged.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        In the first type (106.15-19), the dreamer&apos;s intellect contemplates <i>ta onta</i> while the soul enfolds (<i>periechei</i>) the logoi of all existing things into itself. By <i>ta onta</i> Iamblichus means, of course, the Forms, which reside at the level of the Demiurgic Intellect; the <i>logoi</i> are the active reason principles of the Demiurge at work within the cosmos.<sup><font size=2>16</font></sup> In <i>de An</i>. 365.22-366.5, Iamblichus explains his theory of the soul as a substance existing at a lower level than and being of a different kind from the souls of the gods and other superior beings. One of the defining characteristics of the human soul is that it is the totality of universal reasoning principles (<i>to pleroma ton katholou logon</i>, 3 66.1-2). In <i>Protr</i>. 22.5-6, Iamblichus says that the soul surrounds (<i>periechein</i>) these principles.<sup><font size=2>17</font></sup> Thus, although the human soul is inferior to divine souls, it has within itself the logoi by which it can recognize the Demiurgic <i>logoi</i> and, through them, the Forms themselves. The passage from the <i>de Mysteriis</i> shows that Iamblichus&apos; dream theory depends upon his metaphysical theories. The soul exists at a lower rank (<i>taxis</i>) and possesses <i>logoi</i> appropriate to its rank. By these <i>logoi</i> and with divine aid the soul grasps the Demiurgic <i>logoi</i>. As a result, the dreamer comes to know future events as evidenced in those divine <i>logoi</i>. (This is a neoplatonic reinterpretation of stoic <i>sympatheia</i>.)
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        In the remaining types of <i>theopemptoi</i> dreams that Iamblichus describes, the soul unites with higher divinities and the divination itself improves. The second type is said to make a more perfect divination (106.19-107.5). The intellectual part of the soul unites with the visible gods,<sup><font size=2>18</font></sup> and the gods fill the soul with knowledge of future events that the soul discovers with its own thoughts (<i>ennoiai</i>). In the third type (107.5-10) the dreamer&apos;s soul unites with the intellectual gods<sup><font size=2>19</font></sup> and receives the totality of intellections (<i>pleromata ton noeseon</i>) from which comes true divination. In the fourth type (107.10-16), the soul interweaves its intellectual and divine parts to even higher beings (i.e., to the intelligible gods) and receives even purer images about these gods, about substances incorporeal in themselves, and about intelligibles (<i>noeta</i>). Finally, in the fifth type (107.16-108.3), the soul leads the <i>logoi</i> of existing things to their causes (i.e., to the intelligible gods and the summit of the intelligible realm<sup><font size=2>20</font></sup> and receives knowledge (<i>gnosis</i>) of what will be. Here the soul, existing out of time, attains a synoptic view of things existing in time and even shares in the rank (<i>taxis</i>) of the intelligible gods themselves.<sup><font size=2>21</font></sup>
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        Iamblichus&apos; dream theory is, then, similar to Philo&apos;s but much more elaborate because of the exigencies of the neoplatonic universe. Like Philo, Iamblichus thinks that some dreams are <i>theopemptoi</i> while others originate from ourselves. Like Philo, he subdivides the <i>theopemptoi</i> dreams into several categories. Whereas Philo delineated only three types of <i>theopemptoi</i> dreams, Iamblichus envisions more classifications. There are enthusiasm-type dreams in which the dreamer acts as a mere receptacle for the images of the gods and is completely unaware of what is occurring, as well as similar dreams in which the irrational, sensitive soul of the dreamer is aware of what is going on but the dreamer&apos;s intellect is not involved. Once the dreamer&apos;s intellect is alert to the dream visions, even higher types of <i>theopemptoi</i> dreams and clearer forms of divination occur. In some, the dreamer&apos;s soul contemplates the Forms; in others it is linked to the visible gods, or to the intellectual gods, or to the intelligible gods, or even to the summit of the intelligible realm, the One itself.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        I do not mean to suggest in this paper that Iamblichus read and used Philo&apos;s <i>de Somniis</i>. Just as Philo made use of contemporary middle-Platonic theories to establish his system, so too Iamblichus used and adapted the theories current in his day. Those theories would have included middle-Platonic writings similar to Philo&apos;s. What is remarkable is that the dream theories of Philo and his middle-Platonic contemporaries changed so little in the two hundred years between Philo&apos;s death and Iamblichus&apos; birth.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        <u><b>Notes</b></u>
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        1. I shall cite from the edition of E. des Places (Paris 1966) but retain Parthey&apos;s page numbers.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        2. There is a similarity, too, to <i>Tim.</i> 45e4-46a2, where dreams arise from motions caused when we were awake and that remain after our eyes are closed. Hence, we dream of things we did when we were awake.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        3. I shall discuss Iamblichus&apos; view of enthusiasm shortly.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        4.  Reading <i>geneseos</i> with Ficino. The manuscripts have <i>gnooseos</i>, which des Places retains. If we follow the manuscripts, we must take <i>gnoseos</i> with <i>zoei</i>, not with <i>kechorismenei</i>, and translate "the separated [i.e., from body] life of knowledge." The genitive with kechorismenei seems more natural Greek to me (Iamblichus used it in 106.5), but neither reading alters my point here. A.R. Sodano, Giamblico: I Misteri Egiziani (Milan 1984), 412, defends Ficino&apos;s reading. On the "double life," see Sodano 287 and (with des Places 101 note 2) P. Festugiere, <i>La Revelation d&apos;Hermes Trismegiste</i>, vol. 3, 192 note 2.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        5. Later, at 104.13-105.3, Iamblichus states that these are the very conditions that are most suitable for receiving the gods. See des Places&apos; note 3 <i>ad loc</i>. and  Sodano, op. cit. (note 4), 284-285.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        6. <i>Myst.</i> 1.12, 42.6-17. The gods do not descend, but they do send their "illumination" (<i>ellampsis</i>) to us (40.19-41.4). See des Places&apos; note 2 <i>ad loc</i>. It is interesting to note that Philo, too, does not speak of god descending in the context of these dreams, but of god sending (<i>epipempein</i>) images in sleep (<i>Somn.</i> 1.1), of  our intellect moving with that of the universe (2.2), or of the soul moving from itself (<i>ex heautes he psuche kinoumene</i>, 2.1). The notion may be implicit in the very word <i>theopemptos</i>, "sent by god."
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        7. <i>Ouch hoti ex hemon to kai exothen</i>, i.e., the mantic dream is not even partly from us and partly from outside. It is completely from outside of us.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        8. See also <i>Myst.</i> 3.24, 157.18 and 158.2.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        9. The vehicle of the soul is the body intermediary between the soul itself and the physical body. It is, among other things, the seat of imagination (<i>phantasia</i>) and the means by which the soul may be reunited with the gods in theurgical rites. See my <i>Iamblichus and the Theory of the Vehicle of the Soul</i> (Chico, California 1985), chapters 1 and 4.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        10. Cf. <i>Myst.</i> 3.24, 157.9-11: no human images are set in motion in divination.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        11. See Berchman&apos;s article, above, section 11.2.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        12. For a good overview of the Iamblichean universe, see the introduction to J. M. Dillon, <i>Iamblichi Chalcidensis in Platonis Dialogos Commentariorum Fragmenta</i> (Leiden 1973), 29-52.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        13. All the manuscripts have <i>epipnoias</i> (" inspirations"). It is tempting to read <i>epinoias</i> (&apos;thoughts"). These rational thoughts would contrast more neatly with the <i>pathe</i> ("passions") in the recipient. Thus, in this kind of divination, neither the rational nor the irrational soul would be alert. There is, however, neither need nor sufficient reason to change the manuscripts&apos; reading.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        14. This type of enthusiasm is probably also referred to in <i>Myst.</i> 3.2, 103.14-104.4, where the recipient is aware of the pneuma but where Iamblichus says nothing about the intellect being involved. The fact that the pneuma is said to remove the passions from the recipient&apos;s soul and body (104.5-7) also suggests a person without a strong enough rational soul to keep alert during the divination. If I am correct, then Sodano is wrong when he says that this is a dream of a theurgist, <i>op. cit.</i> (note 4) 286.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        15. See, e.g., <i>Myst.</i> 3.5, on the different kinds of divine possession, esp. 111.11-16. See also <i>Myst.</i> 2.3, where the various kinds of apparitions (<i>phasmata</i>) of gods, demons, angels, archangels, sublunar archons, material archons, and purified souls are discussed. If the apparitions differ, so too would the divination.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        16. For the Forms, see Iamblichus, In <i>Tim.</i> Frr. 7, 29, and 34 and In <i>Parm.</i> Fr. 6A. For logoi, see In <i>Tim.</i> Frr. 9 and 10, and Dillon&apos;s notes <i>ad loc</i>.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        17. Cited by Festugiere, op. cit. (note 4) 185 note 2.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        18. to hola; i.e. the whole souls of the visible gods, as differentiated from "partial" human souls. Cf. Proclus, In <i>Tim.</i> 3.276.19-22 and Finamore <i>op. cit</i> (note 9) 150.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        19. Iamblichus writes simply "gods," but it is clear that he means the intellectual ones because they provide " intellections" (<i>noeseis</i>, 107.8) while the higher (<i>kreittones</i>, 107.12) gods of the fourth type of dream provide noeta (107.15). The intellectual gods are intermediary between the visible and intelligible gods. See Finamore <i>op. cit.</i> (note 9) 134-140. Sodano <i>op. cit.</i> (note 4) 287-288, who sees a three-part division of dreams, thinks that the gods referred to here are the same as those in the second type of dream. Sodano, however, fails to see the complete hierarchy of dreams from 105.15 to 108.3 and is wrongly trying to fit Iamblichus&apos; schema to Posidonius&apos; (<i>ap. Cicero, Div.</i> 1.64).
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        20. The Iamblichean universe is a complex place. The reasoning principles are the active side of the Demiurge and the Forms at work within the cosmos. The Forms and Demiurge are intellectual entities and are, in one sense, the cause of the logoi. There is, however, more to the story. In Phil. Fr. 4, Iamblichus locates what he calls "the monads of the Forms" in the first moment of the intelligible triad, being (<i>on</i>). Now, the monads of the Forms are the Forms pre-existing in a unitary stage before they are distinguished into several Forms (<i>to hekastou adiakriton</i>). They are the causes of the Forms (<i>ousias aitios eidetikes</i>). They could also, therefore, be termed causes of the <i>logoi</i>. Thus, the soul in the fifth type of <i>theopemptos</i> dream may ascend to the summit of the intelligible realm. For more on the interconnection of realms and the soul&apos;s ascent to the One, see Finamore <i>op. cit.</i> (note 9) 140-151.
                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                        21. The human soul does not, of course, become divine. It retains its own rank, but through the help of the gods, associates with them. See Iamblichus, <i>de An.</i>
                                                                                                                                                                                                                                                                                                                                                      </p>