--- 
wordpress_id: 1919
layout: post
title: Lakshmi Puja
date: 2003-10-11 05:21:00
wordpress_url: http://www.arcanology.com/2003/10/11/lakshmi-puja/
---
After a rather hectic day at work with my newly enlarged team (which is causing me severe headaches), <lj user="samajh"> and I managed to have a nice evening.</lj> 
                                                                                                                                                        
                                                                                                                                                        <a href="http://www.psychicsophia.com/forestyurt.html"><img src="http://www.psychicsophia.com/yurtside1.JPG" align="right" border="1" height="108" hspace="10" vspace="10" width="157" /></a>We went out to <lj user="aion131">'s place, which isn't too far from ours. He and his wife, Sophia, have a longish lot in the city, which is common in their neighborhood. The back of it is adjacent to a park, so it is wooded on both sides of the property line. In the midst of this, they've built a deck and put up a yurt, which is dedicated as a temple space. See <a href="http://www.psychicsophia.com/forestyurt.html">http://www.psychicsophia.com/forestyurt.html</a> for details. </lj> Every month, on the full moon, they do a puja for Lakshmi, along with other rituals or events that go on there. R and I had been invited so we headed out right after work. It's a chance to potluck with people, do a little ritual work and generally have a nice evening. I had an opportunity to do a ganapuja with the local Dzogchen Community but this was something R and I could do together with friends. The ritual went well and then Aion, Shade, and I were able to hang out and chat about various things. I met Eric, another one of the original set of Horus-Maat Lodge people that has been part of that crew for 20+ years. I got to hear some hair-raising stories about some of the ritual work they did, such as doing pujas in art museums during Shiva exhibits, etc. I find it somewhat empowering to know a few magicians who I respect and who have been doing this sort of thing for 30 years or so. It gives me hope for the future. On another note, we named the ferret. Her name is "Thalia" now. This had been a topic of some debate in the household.