--- 
wordpress_id: 1831
layout: post
title: The Power of Science
date: 2003-08-02 18:07:00
wordpress_url: http://www.arcanology.com/2003/08/02/the-power-of-science/
---
From <a href="http://www.cs.wisc.edu/~kovar/hall.html">http://www.cs.wisc.edu/~kovar/hall.html</a> <strong> </strong> <h1>
                                                                                                                                                        <center>
                                                                                                                                                          <strong> Electron Band Structure In Germanium, My Ass </strong>
                                                                                                                                                        </center>
                                                                                                                                                      </h1>
                                                                                                                                                      
                                                                                                                                                      <strong>Abstract: The exponential dependence of resistivity on temperature in germanium is found to be a great big lie. My careful theoretical modeling and painstaking experimentation reveal 1) that my equipment is crap, as are all the available texts on the subject and 2) that this whole exercise was a complete waste of my time. </strong> <u> </u> <h3>
                                                                                                                                                        <u>Introduction</u>
                                                                                                                                                      </h3><u></u> Electrons in germanium are confined to well-defined energy bands that are separated by "forbidden regions" of zero charge-carrier density. You can read about it yourself if you want to, although I don't recommend it. You'll have to wade through an obtuse, convoluted discussion about considering an arbitrary number of non-coupled harmonic-oscillator potentials and taking limits and so on. The upshot is that if you heat up a sample of germanium, electrons will jump from a non-conductive energy band to a conductive one, thereby creating a measurable change in resistivity. This relation between temperature and resistivity can be shown to be exponential in certain temperature regimes by waving your hands and chanting "to first order". 
                                                                                                                                                      
                                                                                                                                                      <h3>
                                                                                                                                                        <u>Experiment procedure</u>
                                                                                                                                                      </h3><u></u> I sifted through the box of germanium crystals and chose the one that appeared to be the least cracked. Then I soldered wires onto the crystal in the spots shown in figure 2b of Lab Handout 32. Do you have any idea how hard it is to solder wires to germanium? I'll tell you: real goddamn hard. The solder simply won't stick, and you can forget about getting any of the grad students in the solid state labs to help you out. Once the wires were in place, I attached them as appropriate to the second-rate equipment I scavenged from the back of the lab, none of which worked properly. I soon wised up and swiped replacements from the well-stocked research labs. This is how they treat undergrads around here: they give you broken tools and then don't understand why you don't get any results. 
                                                                                                                                                      
                                                                                                                                                      <table valign="TOP" align="right" border="0" hspace="0" vspace="0" width="300">
                                                                                                                                                        <tr align="left" valign="top">
                                                                                                                                                          <td rowspan="3">
                                                                                                                                                          </td>
                                                                                                                                                          
                                                                                                                                                          <td>
                                                                                                                                                            <img src="http://www.cs.wisc.edu/~kovar/fittedHall.gif" align="bottom" border="1" height="285" width="351" />
                                                                                                                                                          </td>
                                                                                                                                                        </tr>
                                                                                                                                                        
                                                                                                                                                        <tr>
                                                                                                                                                          <td>
                                                                                                                                                             
                                                                                                                                                          </td>
                                                                                                                                                        </tr>
                                                                                                                                                        
                                                                                                                                                        <tr>
                                                                                                                                                          <td>
                                                                                                                                                            <strong><font face="Arial, Geneva, Helvetica, sans-serif" size="2"> Fig. 1: Check this shit out.</font></strong><strong></strong>
                                                                                                                                                          </td>
                                                                                                                                                        </tr>
                                                                                                                                                      </table> In order to control the temperature of the germanium, I attached the crystal to a copper rod, the upper end of which was attached to a heating coil and the lower end of which was dipped in a thermos of liquid nitrogen. Midway through the project, the thermos began leaking. That's right: I pay a cool ten grand a quarter to come here, and yet they can't spare the five bucks to ensure that I have a working thermos. 
                                                                                                                                                      
                                                                                                                                                      <h3>
                                                                                                                                                        <u>Results</u>
                                                                                                                                                      </h3><u></u> Check this shit out (Fig. 1). That's bonafide, 100%-real data, my friends. I took it myself over the course of two weeks. And this was not a leisurely two weeks, either; I busted my ass day and night in order to provide you with nothing but the best data possible. Now, let's look a bit more closely at this data, remembering that it is absolutely first-rate. Do you see the exponential dependence? I sure don't. I see a bunch of crap. Christ, this was such a waste of my time. Banking on my hopes that whoever grades this will just look at the pictures, I drew an exponential through my noise. I believe the apparent legitimacy is enhanced by the fact that I used a complicated computer program to make the fit. I understand this is the same process by which the top quark was discovered. 
                                                                                                                                                      
                                                                                                                                                      <h3>
                                                                                                                                                        <u>Conclusion</u>
                                                                                                                                                      </h3><u></u> Going into physics was the biggest mistake of my life. I should've declared CS. I still wouldn't have any women, but at least I'd be rolling in cash.