--- 
wordpress_id: 244
layout: post
title: Nuit and Mom
date: 2004-09-26 02:25:27
wordpress_url: http://www.arcanology.com/?p=244
---
I see that my mother's article on Nuit for 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <b>The Scarlet Letter</b> is available online now. <a href="http://www.scarletwoman.org/scarletletter/v7n2/v7n2_nuit.html">http://www.scarletwoman.org/scarletletter/v7n2/v7n2_nuit.html</a>. As some of you know, my mother spoke on Nuit at Notocon, the OTO national convention, last year, as well as doing a version of that presentation here in Seattle last fall. She's also written a ritual, <b>The Vespers of Nuit</b>, that a number of people and groups have begun performing from time to time over the last year or two. Nuit is her bag and I encourage interested parties to read her article.