--- 
wordpress_id: 305
layout: post
title: Lost Cyberpunk Futures
date: 2004-12-02 16:17:16
wordpress_url: http://www.arcanology.com/?p=305
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Someone at work asked me to post this...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <img border="1" src="http://www.zhangzhung.net/pics/not-the-future-v2.jpg" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>