--- 
wordpress_id: 143
layout: post
title: An Alan Moore Interview
date: 2004-06-16 23:14:00
wordpress_url: http://www.arcanology.com/?p=143
---
<p>
                                                                                                                                                                                                                                                                                                                                                              A two part interview with Alan Moore is available from a bit over a year ago. Good stuff.
                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            <blockquote>
                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                <i>"But, yes, I will be putting distance between my mainstream comics career and my magical work, simply by closing down my mainstream comics career and becoming a full-time magician."</i>
                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                            </blockquote>
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                              <a href="http://www.ninthart.com/display.php?article=532">Snake Charmer: An Interview with Alan Moore, Part 1</a>
                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                              <a href="http://www.ninthart.com/display.php?article=536">Snake Charmer: An Interview with Alan Moore, Part 2</a>
                                                                                                                                                                                                                                                                                                                                                            </p>