--- 
wordpress_id: 270
layout: post
title: Honeymoon Pictures at Last!
date: 2004-10-24 18:24:49
wordpress_url: http://www.arcanology.com/?p=270
---
I've spent umpteen hours (like five or so) in the last day cleaning up raw pictures, discarding a bunch, tweaking exposure, and then making web versions at lower dpi of the pictures that I took on the honeymoon. I've decided that Adobe and Photoshop can suck my dick, by the way. Their fuckups and craziness caused me to have to redo a bunch of work and do a bunch more from scratch (did you know if your picture is too large on certain dimensions, when you open it is Photoshop, it won't just scale the view but it will turn your picture 90 degrees clockwise?!? WTF!!!). I also managed to crash Digital Image Suite 10 from my employers within ten minutes of beginning heavy duty editing with about 250 MB of images loaded. I had friends who worked on this one that I'll be having words with tomorrow since you'd think someone would have load tested it but I digress... The gallery is up at 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="http://www.zhangzhung.net/italy/">http://www.zhangzhung.net/italy/</a>. If you see any issues, let me know. If you want to critisize my non-existant skills as a photographer, you may risk my wrath. It took me about a week to even figure out how to get certain functions to work right. <center>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img src="http://www.zhangzhung.net/italy/images/milan-5.jpg" width="575" height="766" border="1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </center>