--- 
wordpress_id: 232
layout: post
title: Democracy in Action
date: 2004-09-09 23:15:39
wordpress_url: http://www.arcanology.com/?p=232
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                This is what Democracy looks like!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img border="0" src="http://www.zhangzhung.net/pics/monkey-rodeo.jpg" width="324" height="220" alt="Monkey!" hspace="2" vspace="2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hail to the Chief!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>