--- 
wordpress_id: 94
layout: post
title: The World As It Truly Is
date: 2004-04-29 23:14:00
wordpress_url: http://www.arcanology.com/?p=94
---
<P>
                                                                                                                                                                                                                                                                                                                                                          I didn't read about this until just a minute ago, <STRONG>after</STRONG> my last post, but I just the entry from a blogging acquaintance, someone that I may only have ever vaguely met in person but who I've talked to online for a while, about how she's fallen prey to her heroin addiction again. She's coming clean to her friends and trying to work out her shit and she's obviously being ridden hard by what's been happening to her.
                                                                                                                                                                                                                                                                                                                                                        </P>
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        <P>
                                                                                                                                                                                                                                                                                                                                                          And, you know, it's just tragic and fucked up and about all that I think of to confirm how shitty the world can be sometimes. I feel compassion for her pain and sorrow for what she's going through but, I'm afraid to admit, it's all mixed up with my disgust at another junkie not able to stay away. Not disgust with her but for the whole situation.
                                                                                                                                                                                                                                                                                                                                                        </P>
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        <P>
                                                                                                                                                                                                                                                                                                                                                          She doesn't deserve to die alone but I'm afraid she will and I just want to get away from it, no matter how heart wrenching it is to read about her struggle to get clean again.
                                                                                                                                                                                                                                                                                                                                                        </P>
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        <P>
                                                                                                                                                                                                                                                                                                                                                          You want to know what the flaw that runs through the heart of the World is? Ask her. I think she's got a good fucking view right now. She's looking at the flaw whenever she looks in the fucking mirror.
                                                                                                                                                                                                                                                                                                                                                        </P>
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        <P>
                                                                                                                                                                                                                                                                                                                                                          If she's lucky, she'll kick her habit again. If she's not, she'll be buried and she'll just be one more junkie that people shake their heads about and try to forget without ever wondering too closely about if it could be them or one of their loved ones.
                                                                                                                                                                                                                                                                                                                                                        </P>
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        <P>
                                                                                                                                                                                                                                                                                                                                                          How many will be lost along the way? I wonder about this every few years as I watch people, weak people (but who isn't weak when it comes to it? Me? Right. Bullshit.), fall prey to the demons of our world. I blame society. I blame family. I blame our culture but in the end, it doesn't really fucking matter. It's another lost brother or sister, father or mother, son or daughter. It's you and it could be me and that's the way of this world, for better or worse, regardless of if it was ever better or worst than this.
                                                                                                                                                                                                                                                                                                                                                        </P>
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        <P>
                                                                                                                                                                                                                                                                                                                                                          Be strong, Sister.
                                                                                                                                                                                                                                                                                                                                                        </P>