--- 
wordpress_id: 194
layout: post
title: See you next week!
date: 2004-07-27 23:37:23
wordpress_url: http://www.arcanology.com/?p=194
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Ho!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                In a little over eight hours, I will be on a plane to New Jersey. Once I land, I'll be picked up by Inominandum, my evil twin. We'll be going to meet others in our little tantric society for a small retreat in upstate New York being done by us at a campground. Just eight or ten of us, a teacher who is also a friend of a number of the members, a bunch of ritual paraphernalia and some Buddhism with an attitude.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                I've got two large duffle bags of camping stuff, my portable espresso maker and a pound of coffee. I'm ready to go.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                See you in about six days...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img border="1" src="http://www.arcanology.com/images/twins5-smaller.jpg" width="456" height="372" alt="Separated at birth?" hspace="3" vspace="3" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>