--- 
wordpress_id: 165
layout: post
title: Music and the Dharma
date: 2004-07-07 22:44:01
wordpress_url: http://www.arcanology.com/?p=165
---
I finally got around to ripping all of the Nick Cave CDs we had in the house this weekend. I've been sorting them and fixing the metadata this evening. Seeing Blixa the other month reminded me that I needed to get the Nick Cave stuff on the computer. R has always been the Nick Cave fan in our family but it is a lack that I've been aware of and am now working to rectify. I can't think of any other music that I'd want to commit atrocities while listening more than this... I'm almost through 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <strong>The Cowl</strong> by Neal Asher. So far, I'm liking it quite a bit more than <strong>Gridlinked</strong> or his last novel, <strong>Line of Polity</strong>. Having a new subject matter seems to have done him some good. Tonight was a late work evening with me signing for our brought in dinner as we worked so I've only been home since nine or so. I suspect that I'll be up relatively late though. In a few weeks, I'll be going to Woodstock, NY to camp out with a number of my online friends who are both occultists and Dharma followers. A friend of one of my buddies, <a href="http://www.vajranatha.com/">John Reynolds</a>, will be teaching, though in a relaxed manner, at our campout. These are some of the same people that I did my retreat with last fall. We're looking at it as a retreat but plan on keeping it rather relaxed and somewhat informal. I'm considering whether I want to bring a couple of pieces of equipment and record Reynolds speaking or not. I should probably talk to him or the others and see what they think.