--- 
wordpress_id: 289
layout: post
title: Hacking Yourself
date: 2004-11-20 16:03:56
wordpress_url: http://www.arcanology.com/?p=289
---
I found an excellent essay on "Hacking Yourself" online today. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      You don't exist. You just think you do. We're nothing but the stories we tell ourselves. We know in our hearts what kind of people we are, what we're capable of, because we've told ourselves what kind of people we are. You're a carefully-rehearsed list of weaknesses and strengths you've told yourself you have.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </blockquote> Read the rest at 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="http://www.bloodletters.com/hackyourself.shtml">http://www.bloodletters.com/hackyourself.shtml</a>.