--- 
wordpress_id: 62
layout: post
title: Beginning of Week
date: 2004-03-17 00:48:00
wordpress_url: http://www.arcanology.com/?p=62
---
It's all getting fuzzy now but this wekend, R and I went and had our taxes done by a professional because of the purchase of the house, etc. this last year. Following that, on Saturday, we went and saw Lazuli93 at her work and had massages done there, which was quite nice. I should do that more often. Sunday is largely a blur but perhaps I'm just tired... I know that I stayed home most of the day but the guys came over for an evening of ritual work (a pathworking, effectively, for Sol and another rite). That ate up a big chunk of the evening. I did manage to work through 
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        <strong>White Wolf</strong>, the new David Gemmel fantasy between Friday evening and Sunday afternoon. It's a pretty typical book for him and I enjoyed it. It definitely didn't really cover any new ground. I'm currently reading <strong>The Golden Trancendence</strong>, which is the final book in a trilogy that I started this last year. A "What if we lived in a Utopia, what would the crimes be?" kind of novel. I actually think it is quite good and I enjoyed the first two books in the series. I've also been reading <strong>The Golden Letters</strong> by John Reynolds (well, translated by him with commentary by him) as well. I'm hoping to go on a retreat with him this summer if things line up well. Tonight, I rushed from work over the bridge to Seattle to sign my tax paperwork so it can be all filed. I'm getting about half the return that I expected, which bites, but I'll be able to use it to pay for much of the wedding in October. After paperwork, I went over to Oniyeh and Ashley's place for some OTO training and hung out with them and Matertiamat afterwards drinking wine and chanting. On the way home, I tried to drop off a library book that the King County Library System is thinking I've lost but it turns out that the local library closed on March 1 for renovation and doesn't even have a drop box now. I need to get this book in though...ah well. I did run into the wonderful Rubylou and Drakemonger at Third Place (where the library is). They were attending the Tuesday night Poly coffee meetup. It was nice to see the two of them and she and I need to have coffee again soon. The third was home with the baby while the two of them went out. That's about it for now...