--- 
wordpress_id: 318
layout: post
title: Should I be offended or amused?
date: 2004-12-12 12:15:11
wordpress_url: http://www.arcanology.com/?p=318
---
Some weird intersection between D&D and Gay Culture? :-) 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="http://blog.codefront.net/archives/2004/12/13/cone-of-gayness/" target="_top">http://blog.codefront.net/archives/2004/12/13/cone-of-gayness/</a> <center>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img src="http://www.arcanology.com/images/cone-of-gayness.png" alt="Cone of gayness" border="1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </center>