--- 
wordpress_id: 197
layout: post
title: Morons Among Us
date: 2004-08-07 14:37:38
wordpress_url: http://www.arcanology.com/?p=197
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                And I laughed and laughed and laughed...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="http://www.amazon.com/exec/obidos/tg/detail/-/1578633214/">Psychic Vampire Codex: A Manual of Magick and Energy Work</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img border="1" src="http://images.amazon.com/images/P/1578633214.01.LZZZZZZZ.jpg" hspace="3" vspace="3" width="333" height="500" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                As a member of a spiritual minority and an unabashed freak for weird religious thought, is it a bad thing that I look at this book and can't stop laughing? Where did my acceptance of other people's weird ideas go? Of course, on the other hand, only an utter moron would buy this work...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>