--- 
wordpress_id: 298
layout: post
title: Picture of the Day from AP
date: 2004-11-26 18:45:12
wordpress_url: http://www.arcanology.com/?p=298
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      This speaks volumes about the world:<blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <center>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <img src="http://us.news2.yimg.com/us.yimg.com/p/ap/20041122/capt.mac10311221914.iraq_mosul_mac103.jpg" alt="A happy face smiles back from the scope of a U.S. Army sniper's rifle, during a mission searching for insurgents in Mosul, Iraq, Monday, Nov. 22, 2004. U.S. and Iraqi forces in Mosul have been working put down an uprising launched by guerrillas who seized police stations and other sites. (AP Photo/Jim MacMillan)" align="middle" border="1" height="273" width="410" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </center>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          A happy face smiles back from the scope of a U.S. Army sniper's rifle, during a mission searching for insurgents in Mosul, Iraq (<a href="http://us.rd.yahoo.com/DailyNews/manual/*http://news.search.yahoo.com/search/news?fr=news-storylinks&p=%22Iraq%22&c=&n=20&yn=c&c=news&cs=nw">news</a> - <a href="http://us.rd.yahoo.com/DailyNews/manual/*http://search.yahoo.com/search?fr=web-storylinks&p=Iraq">web sites</a>), Monday, Nov. 22, 2004. U.S. and Iraqi forces in Mosul have been working put down an uprising launched by guerrillas who seized police stations and other sites. (AP Photo/Jim MacMillan)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </blockquote>