--- 
wordpress_id: 362
layout: post
title: Gotta love Bakunin
date: 2005-01-08 12:45:03
wordpress_url: http://www.arcanology.com/?p=362
---
A friend sent me this. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      The State will no longer call itself Monarchy; it will call itself Republic: but it will be none the less the State - that is, a tutelage officially and regularly established by a minority of competent men, men of virtuous genius or talent, who will watch and guide the conduct of this great, incorrigible, and terrible child, the people. The professors of the School and the functionaries of the State will call themselves republicans; but they will be none the less tutors, shepherds, and the people will remain what they have been hitherto from all eternity, a flock. Beware of shearers, for where there is a flock there necessarily must be shepherds also to shear and devour it.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </blockquote> -- Bakunin, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="http://flag.blackened.net/daver/anarchism/bakunin/gas.html">God and the State</a>