--- 
wordpress_id: 348
layout: post
title: Contractors in the Morning
date: 2005-01-03 10:37:07
wordpress_url: http://www.arcanology.com/?p=348
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I woke up this morning (and the wife did) to an 8:00 AM phone call. It's the contractor, who was going to come Wednesday, saying his three day job got cancelled and would I like him to fix my ceiling and wall in the bathroom today?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    We said "Yes!" I have the day off as MS gave me today off for New Year's instead of Friday. This means that I won't have to miss a morning of work on Wednesday, which is good.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Since he's here, I had him look at the dishwasher problem briefly. It looks like the shutoff for it from the sink is rusted open too. :-)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    So, when he gets done in the bathroom (he's been here and hour or so and is about done), we'll probably turn off the water to the house and try to disconnect things. Getting a professional to look at the floor damage while he's already here (saving a trip and minimum fee) seems like a good idea. I'd like to get the dishwasher pulled out anyway. He thinks that if the damage isn't extensive, it's probably easy to fix the plywood flooring though. We'll see once it is exposed.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>