--- 
wordpress_id: 600
layout: post
title: Nearly Finished with my Current Paper
date: 2005-11-21 21:55:05
wordpress_url: http://www.arcanology.com/?p=600
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                The first draft of my second (of three) papers for my <strong>Individual and Society</strong> class was completed by me today. That only took me most of today and much of yesterday but I was probably only working 50% on it with other things going on both days. That leaves me one to go, which I may start on tomorrow.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                I think I've had enough reading about utopias for a while. I feel like I should go read some William Gibson to compensate but then I always did like the Panther Moderns.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                For the final paper in the <strong>Para-Rational Perspectives</strong> class, the professor also mentioned in his e-mail earlier today that I could turn it in by e-mail by the seventh, rather than the second, though earlier is better. Not having to physically mail this one means that I'm not in quite as much of a time crunch to do it. That's all good news.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>