--- 
wordpress_id: 479
layout: post
title: More Meditation Studies
date: 2005-06-09 17:05:54
wordpress_url: http://www.arcanology.com/?p=479
---
From 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="http://www.eurekalert.org/pub_releases/2005-06/ra-tmy060705.php"> http://www.eurekalert.org/pub_releases/2005-06/ra-tmy060705.php</a> <h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Tibetan monks yield clues to brain's regulation of attention
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h2> University of Queensland researchers have teamed up with Tibetan Buddhist monks to uncover clues to how meditation can affect perception. Olivia Carter and Professor Jack Pettigrew from UQ's Vision, Touch and Hearing Research Centre, as well as colleagues from the University of California Berkeley, found evidence that skills developed by the monks during meditation can strongly influence attention and consciousness. With the support of His Holiness the Dalai Lama, 76 monks participated in the study, which was carried out at or near their mountain retreats in the Himalaya, Zanskar and Ladakhi Ranges of India. Ms Carter said the study was aimed at gaining an insight into how visual perception is regulated within the brain. She said the research investigated the extent that certain types of trained meditative practice can influence the conscious experience of visual perceptual rivalry, which is what happens when someone has two different images shown to each eye, or is shown an ambiguous image such as a picture that can look like two faces or a vase. "Typically this results in a switching between the two images, but in the case of one type of meditation, the monks reported a perceptual dominance of one of the images," Ms Carter said. The researchers tested the experience of visual rivalry by monks during practice of two types of meditation: a "compassion"-oriented meditation, described as a contemplation of suffering within the world combined with an emanation of loving kindness, and "one-point" meditation, described as the maintained focus of attention on a single object or thought that leads to a stability and clarity of mind. While no observable change in the rate of "visual switching" during rivalry was seen in monks practicing compassion meditation, major increases in the durations of perceptual dominance were experienced by monks practicing one-point meditation. "Our findings suggest that processes particularly associated with one-point meditation, perhaps involving intense attentional focus and the ability to stabilize the mind, contribute to this ability of the monks," Ms Carter said. She said the study showed individuals trained in meditation can considerably alter their perception.