--- 
wordpress_id: 554
layout: post
title: The Color Answer to Jack Chick Tracks
date: 2005-09-13 20:56:19
wordpress_url: http://www.arcanology.com/?p=554
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          This is almost enough for me to wish that I was gay...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://www.thetruthforyouth.com/standard/main.htm">http://www.thetruthforyouth.com/standard/main.htm</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <img width="519" height="795" border="1" align="center" src="http://www.thetruthforyouth.com/NEW%20Comics/bw/images/BTW_6.jpg" alt="Anti-Homosexual Comic" title="Anti-Homosexual Comic" /> 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>