--- 
wordpress_id: 642
layout: post
title: Afterculture
date: 2005-12-19 02:17:54
wordpress_url: http://www.arcanology.com/?p=642
---
I love Michael Green's 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <strong><a href="http://art.afterculture.org/">Afterculture</a></strong> exhibits and work. I wish that more of his work was available as I find his vision (whether realistic or not) of a post-collapse series of societies to be more positive than many of them are... <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img src="http://www.arcanology.com/images/Standing-stone-painted.jpg" alt="Standing Stone" border="1" height="504" width="311" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>