--- 
wordpress_id: 480
layout: post
title: Bruce Campbell
date: 2005-06-10 22:21:20
wordpress_url: http://www.arcanology.com/?p=480
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Bruce Campbell will be speaking at my work in a couple of weeks. He's also doing a public appearance. I plan to attend one of these.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </P>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Seattle, WA<br />Monday, June 27, 2005 <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="http://bruce-campbell.com/images/filmography/make-love.jpg" /><p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      University Bookstore & /Neptune Theatre at 6:00pm<br />Make Love the Bruce Campbell Way signing<br />Man with the Screaming Brain screening<br />At Neptune Theatre, 1303 N.E. 45th, Seattle, WA 98105 (map)<br />(206) 781-5755<br />www.landmarktheatres.com