--- 
wordpress_id: 506
layout: post
title: Lovecraft, meet Tentacle Porn
date: 2005-07-07 10:07:01
wordpress_url: http://www.arcanology.com/?p=506
---
Lovecraft is spinning like a turbine in his grave. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <A href="http://www.eos-press.com/spotlight-ctech.html">http://www.eos-press.com/spotlight-ctech.html</A> <h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Spotlight: CthulhuTech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h2><img hspace=10 src="http://www.arcanology.com/images/ctech-250.jpg" align="right" border="1"> 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <B>Mythos & Mecha Meet </B> The strange aeon has come. The human species fights to survive against the incursion of the Fungi from Yuggoth, the power of the Cults, and the darkness of the recently arisen Great Old Ones. But humanity, ever-adaptable, is far from helpless... having learned some of the very knowledge of the enemy. Giant arcanotechnology war machines—mecha by any other name—close the gap between between survival and mythos domination. <B>The Aeon War Rages </B> CthulhuTech is a seamless melding of the eldritch horror inspired by H. P. Lovecraft, and Japanese mecha anime the likes of Robotech, the Guyver, or Neon Genesis: Evangelion. This storytelling game puts players in the thick of the Aeon War—Humanity's last stand to hold Earth and survive against dominance by the Mi-Go and the Great Old Ones. Whether it's getting in the cockpit of a sleek NEG mech, storming into battle in a powerful mythos-hybrid Engel, or waging shadow wars as a mythos-symbiote Tager [pictured at right], CthulhuTech takes players into a new and exciting world formed from their favorite influences. Black Sky Studios has joined forces with Sam Araya and other fine artists to bring you CthulhuTech. The CthulhuTech Core Book contains everything you need to begin play, in a densely-packed hardbound book of high quality with beautiful art. Further supplements are also being planned. <B>CthulhuTech Core Book</B> Hardcover, 240 pp. Release Date: TBA Retail Price: $34.95