--- 
wordpress_id: 516
layout: post
title: V for Vendetta Trailer
date: 2005-07-27 15:38:27
wordpress_url: http://www.arcanology.com/?p=516
---
A trailer is finally out. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="http://vforvendetta.warnerbros.com/trailer.html">http://vforvendetta.warnerbros.com/trailer.html</a> The direct link to the Quicktime 6 version (you need QT7 for the High Definition version) is <a href="http://vforvendetta.warnerbros.com/cmp/trailer_lrg.html">http://vforvendetta.warnerbros.com/cmp/trailer_lrg.html</a>.