--- 
wordpress_id: 595
layout: post
title: Classic Picture
date: 2005-11-17 10:51:20
wordpress_url: http://www.arcanology.com/?p=595
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  I work for this guy and I still love this picture.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p><p align=center><img src="http://www.arcanology.com/images/billg-surprise.jpg" border=1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>