--- 
wordpress_id: 366
layout: post
title: My eyeball or yours?
date: 2005-01-13 22:11:28
wordpress_url: http://www.arcanology.com/?p=366
---
 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="http://www.zhangzhung.net/lj/eyeball.jpg" alt="A big nut" align="right" border="1" hspace="5" vspace="10" />I'm into cool architecture and all but <a href="http://www.freespiritspheres.com/index.htm">this</a> is just the weirdest thing that I've seen in a while. It makes me think of either James and the Giant Peach or a giant eyeball in the woods. I need something like five acres of forested land and twenty of these with catwalks...<br clear="all" />