--- 
wordpress_id: 1420
layout: post
title: I didn't know that I caused so much trouble...
date: 2006-10-25 20:58:22
wordpress_url: http://www.arcanology.com/?p=1420
---
I found this on <a href="http://feeds.wired.com/~r/wiredbeyond/~3/41446750/overheard_at_id.html">Bruce Sterling's blog</a> today. It is a quote from the IDEA2006 conference, overheard: <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "People spend whole days of their lives on the phone, dealing with billings... It's just an incredibly arduous experience."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </blockquote> I apologize to one and all for being arduous...