--- 
wordpress_id: 1488
layout: post
title: Pithy Crowley Quote
date: 2006-12-23 00:50:31
wordpress_url: http://www.arcanology.com/?p=1488
---
I found this pithy quote from ol' Uncle Aleister today: <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              I admit that my visions can never mean to other men as much as they do to me. I do not regret this. All I ask is that my results should convince seekers after truth that there is beyond doubt something worth while seeking, attainable by methods more or less like mine. I do not want to father a flock, to be the fetish of fools and fanatics, or the founder of a faith whose followers are content to echo my opinions. I want each man to cut his own way through the jungle.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </blockquote> - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="http://www.hermetic.com/crowley/confess/"><strong>The Confessions of Aleister Crowley</strong></a>, <a href="http://www.hermetic.com/crowley/confess/chapter66.html">Chapter. 66</a> Makes one ponder the fruits of his labor and the work of his followers.