--- 
wordpress_id: 660
layout: post
title: Cool Tattoos
date: 2006-01-06 01:57:35
wordpress_url: http://www.arcanology.com/?p=660
---
<p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          I guess I missed out on getting a tattoo when I was in Thailand. If there was a place to go, apparently it is Wat Bang Phro.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          There is a photoessay about the tattooing their at <a href="http://home.att.net/~t.elsawy/TattooingMonks_Intro.html">http://home.att.net/~t.elsawy/TattooingMonks_Intro.html</a>.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>