--- 
wordpress_id: 1437
layout: post
title: Research on Speaking in Tongues
date: 2006-11-08 14:52:42
wordpress_url: http://www.arcanology.com/?p=1437
---
The New York Times had <a href="http://www.nytimes.com/2006/11/07/health/07brain.html">an article</a> recently on "Speaking in Tongues," which is also known as "Glossalalia." This is a topic that has interested me ever since I read Felicitas Goodmans' book on the topic that is derived from her doctoral dissertation years ago. That book covers here academic work where she went and compared vocal patterns in Pentacostal groups between native English speakers and native Spanish speakers to try to determine if the sounds created during sessions were language dependent or not. My friend, Richard, once new a witch (I believe) back in the 1970's or so that used glossalalia as a technique in her spiritual work even though she was not a Christian. Since that time, I've heard of Chaos magicians, such as Jan Fries, espousing this as well. If I was 18 and into developing a new career for myself, I would considering going into neuroscience. There is an incredible amount of work being done on meditative or altered states of consciousness, especially now that the tools are so much better. Interesting stuff. <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img src="http://www.zhangzhung.net/lj/1107-sci-webBRAIN.jpg" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>