--- 
wordpress_id: 1418
layout: post
title: What about Iraq?
date: 2006-10-23 23:27:49
wordpress_url: http://www.arcanology.com/?p=1418
---
I must admit that Tyrone cracks me up. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://kfmonkey.blogspot.com/2006/10/lunch-conversations-463-t-shirt-sales.html">http://kfmonkey.blogspot.com/2006/10/lunch-conversations-463-t-shirt-sales.html</a>