--- 
wordpress_id: 1476
layout: post
title: Ken Wilber is in the hospital
date: 2006-12-09 01:10:38
wordpress_url: http://www.arcanology.com/?p=1476
---
Ken Wilber apparently went to the hospital Thursday. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Early Wednesday morning Ken was admitted to a local hospital for repeated seizures and an abnormal cardiac pattern. Ken is currently in stable condition in the Intensive Care Unit.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </blockquote> Read more 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://www.kenwilber.com/blog/show/208">here</a> but there isn't a lot other than he isn't going to die and that it seems to have an acute, but unstated, cause.