--- 
wordpress_id: 1220
layout: post
title: The Spartans
date: 2006-10-05 12:52:22
wordpress_url: http://www.arcanology.com/?p=1220
---
Frank Miller's vision of the Spartan stand at the Battle of Thermopylae against the Persian empire is finally being made into a movie. Remember their epitaph: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Traveler, take this word to the men of Lakedaimon: We who lie buried here did what they told us to do.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </blockquote> The movie looks incredible, though pretty obviously heavily stylized. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://www.apple.com/trailers/wb/300/">http://www.apple.com/trailers/wb/300/</a>