--- 
wordpress_id: 1478
layout: post
title: Amida Nyorai
date: 2006-12-12 00:13:26
wordpress_url: http://www.arcanology.com/?p=1478
---
<p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a title="Photo Sharing" href="http://www.flickr.com/photos/albill/320274356/"><img width="375" height="500" alt="Amida 003" src="http://static.flickr.com/123/320274356_58c5842c5b.jpg" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://en.wikipedia.org/wiki/Amitabha">http://en.wikipedia.org/wiki/Amitabha</a>