--- 
wordpress_id: 1431
layout: post
title: Chichen Itza, Uxmal, and Kabah
date: 2006-11-03 17:01:56
wordpress_url: http://www.arcanology.com/?p=1431
---
Yesterday, R and I took a day trip to Chichen Itza with a group. This meant that we could ride in an air conditioned bus the 100+ kilometers there and relax. We also got a guide out of the deal. The site was pretty impressive but very crowded. I took many photos but I won't be uploading them to Flickr until we get back to Oakland in a couple of days. Today, we went to Uxmal and Kabah, sites to the south of Merida. Uxmal was the seat of a local kingdom and has a very nice pyramid (two actually) and a large square that is well preserved. Kabah was a ritual center from the end of the Uxmal era which, we are told, became important as war and safety concerns caused ritual celebrations to be moved away from the city of Uxmal. We did have someone take one of our few joint photos of the trip at Uxmal: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a title="Photo Sharing" href="http://www.flickr.com/photos/albill/288059243/"><img width="375" height="500" alt="Uxmal - 026" src="http://static.flickr.com/121/288059243_0d209987a0.jpg" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>