--- 
wordpress_id: 1439
layout: post
title: The Prestige
date: 2006-11-10 00:10:07
wordpress_url: http://www.arcanology.com/?p=1439
---
R and I went and saw 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <strong>The Prestige</strong> this evening with some of my coworkers. This was a fairly enjoyable movie. I liked the performances by the actors and seeing David Bowie playing Tesla was amusing. All in all, a good job. I cannot say that I did not see a large portion of the ending ahead of time but it was a good story and a good movie. They showed a preview for <strong>The Fountain</strong> as well. I am excited to see that getting closer to coming out and I really hope that it lives up to the hype. As an aside, we're still in negotiations on the house. There were issues with the front porch, which is all brick, found as when the owners redid the foundation, they left the front alone instead of putting concrete behind the brick. The brick has settled and cracked behind over time and about $20,000 of foundation work needs to be done on it and on some of things below the house. We've offered to split the costs for this with the current owners but it isn't clear that they'll take the deal. It is a soft housing market and they are unlikely to make much, if any money, on this sale as they put a lot into the new foundation and roof but we cannot buy it without this work being agreed to by them. We'll see. If they say, "No," then we will look for another place.