--- 
wordpress_id: 1408
layout: post
title: Rights? We don't need no stinkin' rights.
date: 2006-10-17 22:28:04
wordpress_url: http://www.arcanology.com/?p=1408
---
<blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            One of the terrorists believed to have planned the 9/11 attacks said he hoped the attacks would be the beginning of the end of America. He didn't get his wish.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </blockquote> -- George W. Bush, upon 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://www.whitehouse.gov/news/releases/2006/10/20061017-1.html">signing</a> the Military Commissions Act of 2006 into law.