--- 
wordpress_id: 732
layout: post
title: A Buddhist Story
date: 2006-04-08 03:22:38
wordpress_url: http://www.arcanology.com/?p=732
---
<h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              The Man Born Blind
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h2> There was a man born blind, and he said: "I do not believe in the world of light and appearance. There are no colours, bright or somber. There is no sun, no moon, no stars. No one has witnessed these things." His friends remonstrated with him, but he clung to his opinion: "What you say that you see," he objected, "are illusions. If colours existed I should be able to touch them. They have no substance and are not real. Everything real has weight, but I feel no weight where you see colours." A physician was called to see the blind man. He mixed four simples, and when he applied them to the cataract of the blind man the grey film melted, and his eyes could see. The Tathagatha is the physician, the cataract is the illusion . . . and the four simples are the four noble truths.