--- 
wordpress_id: 1433
layout: post
title: Pagan Store Burned Down in Pacific Northwest
date: 2006-11-06 23:11:17
wordpress_url: http://www.arcanology.com/?p=1433
---
The local pagan bookstore in Everett, Washington burned down recently. It is suspected that it may be arson. This was covered in the 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="http://heraldnet.com/stories/06/11/06/100loc_b1fire001.cfm">local newspaper</a>. Everett is the next major city north of Seattle and I expect that I know people that go to this store on a regular basis. I do hope that if it is arson that they catch the person that did this. It is a shame, to say the least.