--- 
wordpress_id: 1493
layout: post
title: Ken Wilber Up and Around
date: 2006-12-27 00:10:05
wordpress_url: http://www.arcanology.com/?p=1493
---
There is now a blog post that explains what hospitalized Ken Wilber recently (and almost killed him). It sounds like he is doing a lot better, for which I am very glad. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              At 8:30 PM on Tuesday, December 5, 2006, while Becca and I were watching a movie, I had a grand mal seizure that was quite severe. Although these are common with CFIDS/REDD/ME, it has only happened once to me before, as far as I can tell. A really major grand mal seizure can kill you. Although this one didn't do that, it came damn close, and was in any event severe enough to precipitate ten more equally severe seizures-one after another after another. By the time they got me to the ER and stabilized-about 12 hours later-not only had I suffered around a dozen grand mal seizures in a row, I had essentially flat-lined three times and had the electric paddles applied to my chest three times-overall, a pretty gruesome ordeal.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="http://www.kenwilber.com/blog/show/214">http://www.kenwilber.com/blog/show/214</a>