--- 
wordpress_id: 1453
layout: post
title: Homosexuality and the APA
date: 2006-11-19 14:10:53
wordpress_url: http://www.arcanology.com/?p=1453
---
I would recommend to any with the time to listen to 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="http://www.thisamericanlife.org/pages/descriptions/02/204.html">this story</a> on <strong>This American Life</strong> on NPR. It details how the American Psychiatric Association (APA) removed Homosexuality from its list of officially aberrant behaviors, thus freeing homosexuals from being condemned as ill and needing treatment simply for being gay. Until hearing this and some other stories that I had read the last few weeks, I hadn't realized how much had gone into this, including there being a group of closeted men in the APA and that the president-elect at the time of the decision later came out (at age 70 to his family) as gay. When you hear gay men of this generation speak, the level of difficulty in coming out or in even admitting that one is gay becomes very apparent. I've only had one friend who is of this generation but the stories he's mentioned to me in passing and to R in more depth make it <strong>very</strong> clear homosexuals need to be welcomed for who they are instead of attacked for it (as if there was any question of that, in my opinion). No man or woman should have to hide from their own family or their entire professional world simply in order to survive unmolested. Ponder that the next time the Right speaks about "special rights for homosexuals."