--- 
wordpress_id: 1473
layout: post
title: The Face of Terror
date: 2006-12-06 00:45:29
wordpress_url: http://www.arcanology.com/?p=1473
---
This is the face of terror and I don't mean the poor fucker in the orange jumpsuit. He may or may not have done anything. He may or may not ever get a real day in court with a judge and lawyer facing his accusers but this treatment (of a fellow citizen!) is horrific. It's a wonder that he hasn't gone insane in isolation. This is us in the mirror, folks. <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img src="http://www.arcanology.com/images/04detain.jpg" border="1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p> Read about it at the 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://www.nytimes.com/2006/12/04/us/04detain.html?ex=1322888400&en=accb01df2436f791&ei=5090&partner=rssuserland&emc=rss">New York Times</a>.