--- 
wordpress_id: 2145
layout: post
title: Happy Cephalopodmas!
date: 2007-12-22 15:55:05
wordpress_url: http://www.arcanology.com/2007/12/22/happy-cephalopodmas/
---
<a href="http://www.flickr.com/photos/albill/2129878896/" title="little-cthulhu by albill, on Flickr"><img src="http://farm3.static.flickr.com/2391/2129878896_723e6c5cb3_o.png" border="0" align="right" width="208" height="310" alt="little-cthulhu" /></a>I want to wish everyone a <a href="http://www.cephalopodmas.com/">Happy Cephalopodmas!</a> To celebrate the season, I offer a carol for you from the <strong><a href="http://www.cthulhulives.org/Solstice/">HPLHS Solstice Carol Songbook</a></strong>. <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="http://www.cthulhulives.org/Solstice/fish-menplayer.html">It's Beginning to Look a Lot Like Fish-Men</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h2> It's beginning to look a lot like fish-men Everywhere I go; From the minute I got to town And started to look around I thought these ill-bred people's gillslits showed. I'm beginning to hear a lot of fish-men Right outside my door, As I try to escape in fright To the moonlit Innsmouth night I can hear some more. They speak with guttural croaks and to hear them provokes A profound desire to flee Their eyes never blink and quite frankly they stink Like a carcass washed up from the sea. I wish I'd paid attention to that crazy drunken man. He tried to warn me all about old Marsh's Deep One clan. It's beginning to look a lot like Fish-men Everywhere I go; They can dynamite Devil Reef, but that'll bring no relief, Y'ha N'thlei is deeper than they know. I'll continue to see a lot of fish-men That I guarantee. For the fish-man I really fear is the one who's in the mirror And he looks like me. He looks just like me.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </blockquote>