--- 
wordpress_id: 1790
layout: post
title: Cory Doctorow's T-Shirt Available Again
date: 2007-08-27 13:11:03
wordpress_url: http://www.arcanology.com/?p=1790
---
The guys at <a href="http://www.woot.com">Woot</a> have made the t-shirt designed by Cory Doctorow around airline travel available again. Free shipping too. :-) <div align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="http://www.flickr.com/photos/albill/1251137515/" title="Photo Sharing"><img src="http://farm2.static.flickr.com/1273/1251137515_0e4e7f58b9_o.jpg" width="449" height="340" alt="Threat Level (Doctorow) T-Shirt" /></a><br /><a href="http://shirt.woot.com/friends.aspx?k=3630">http://shirt.woot.com/friends.aspx?k=3630</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>