--- 
wordpress_id: 1965
layout: post
title: An Image to Ponder...
date: 2007-10-06 06:46:38
wordpress_url: http://www.arcanology.com/2007/10/06/an-image-to-ponder/
---
<p style="text-align: center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img src="http://www.arcanology.com/images/burma-monks-soldiers2.jpg" border="1" height="280" hspace="0" vspace="0" width="280" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>