--- 
wordpress_id: 1670
layout: post
title: Fire Art of Burning Man
date: 2007-04-18 10:56:35
wordpress_url: http://www.arcanology.com/?p=1670
---
Leonardo Online, a publication of MIT, has an article on the "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="http://leonardo.info/gallery/burningman_fire/burningman.html">Fire Art of Burning Man</a>" up now. I recognize a number of the items there and almost all of them are amazing. My particular favorite is "<a href="http://leonardo.info/gallery/burningman_fire/black.html">The Voice of Fire</a>" by Tim Black. Tim managed to get a set of flames to act as speakes and emit sound through a combination of chemistry and electricity. <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <img src="http://www.arcanology.com/images/Black1_web.jpg" title="The Voice of Fire" alt="The Voice of Fire" border="1" height="450" width="338" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>