--- 
wordpress_id: 1962
layout: post
title: Last Day in Kyoto
date: 2007-10-03 05:52:29
wordpress_url: http://www.arcanology.com/2007/10/03/last-day-in-kyoto/
---
Today was our last day in Kyoto. Tomorrow, we take a series of trains to arrive at Koyasan. We went to the Gion district today to have a peek. While there, we visited Kennin-ji, the oldest Zen temple in Japan. Kennin-ji has a quite nice zen garden in the complex as well as some impressive paintings in the main temple. <p style="text-align: center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://www.flickr.com/photos/albill/1475853446/" title="Photo Sharing"><img src="http://farm2.static.flickr.com/1107/1475853446_8d2b671def.jpg" alt="DSCF1370.JPG" border="1" height="375" width="500" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style="text-align: center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://www.flickr.com/photos/albill/1475865562/" title="Photo Sharing"><img src="http://farm2.static.flickr.com/1138/1475865562_2644bf0a1a.jpg" alt="DSCF1388.JPG" border="1" height="375" width="500" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p> I put a 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="http://www.flickr.com/photos/albill/sets/72157602240996414/">nice set of photos</a> up on Flickr, as per my usual.