--- 
wordpress_id: 2131
layout: post
title: Why we need schools...
date: 2007-12-07 19:20:14
wordpress_url: http://www.arcanology.com/2007/12/07/why-we-need-schools/
---
If there is a sadder demonstration of why we both need schools and some standards for the people we allow to pontificate on television, I don't know what it would be. <lj-embed></lj-embed> From <a href="http://www.foxnews.com/story/0,2933,315194,00.html">Fox News</a> of all places... <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          The new co-host of "The View," Sherri Shepherd, insisted Tuesday that Christianity was older than ancient Greece, and even Judaism. Shepherd - who said earlier this year that she didn't know if the world was flat or round - said during a short-lived discussion of Greek philosophy on Tuesday's show that she was pretty sure nothing "predated Christians." The verbal jousting began when Joy Behar mentioned watching a History Channel show on the Greek philosopher Epicurus and his definition of happiness. "Keep in mind that probably when [Epicurus] was around, there was no Jesus Christ stuff going on," co-host Whoopi Goldberg said. "They still had Christians back then," Shepherd interrupted. "They had gods," Goldberg said. "They had Christians," Shepherd insisted. "And they threw 'em to the lions." "I think this might predate that," Goldberg said. "I don't think anything predated Christians," Shepherd shot back.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </blockquote>