--- 
wordpress_id: 1692
layout: post
title: Attention and the Mind
date: 2007-05-12 15:12:27
wordpress_url: http://www.arcanology.com/?p=1692
---
One of the things that Buddhist meditation is good at teaching, in a practical manner, is that our mind is not the concrete structure that many of us believe it to be. Many things are going on "behind the curtain" that our conscious awareness just glosses over until we are forced to pay attention to it. This helps us create an illusion of day to day reality that often does not really match the real world. A lot of what we perceive of the world is, in fact, made up by our minds without our conscious awareness. I found a youtube video today that demonstrates this as part of a psychological quirks series. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <lj-embed></lj-embed>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div> Watch this video and then ponder the significance of the revelations at the end and what they say about your mind...