--- 
wordpress_id: 1511
layout: post
title: Back from Gonzo
date: 2007-01-06 01:06:19
wordpress_url: http://www.arcanology.com/?p=1511
---
<p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a title="Photo Sharing" href="http://www.flickr.com/photos/albill/347499603/"><img width="500" height="375" alt="Gonzo 1" src="http://farm1.static.flickr.com/146/347499603_cb39bd136b.jpg" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p> We just got back from seeing "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="http://www.gonzoduke.com/">Gonzo: A Brutal Chrysalis</a>" in San Francisco this evening. This turned out to be a one man piece with the actor playing Hunter S. Thompson on stage by himself in Hunter's writing den. It progressed over a period of a number of years through episodes in Thompson's life, ending with him leaving to do his (in)famous Las Vegas trip. I liked it though it was obviously a labor of love for those involved. The key actor (we are not told his name anywhere, only a pseudonym of "B. Duke") memorized roughly an hour and a half of material. When he stuck to his script, it worked pretty well. As R pointed out, some of his in-character improv from time to time was more strained but I thought that it was well done overall. We had a good time at the show.