--- 
layout: post
title: The Destruction of the American Dream
published: true
meta: 
  ljID: "3047"
  _podPressPostSpecific: a:6:{s:15:"itunes:subtitle";s:15:"##PostExcerpt##";s:14:"itunes:summary";s:15:"##PostExcerpt##";s:15:"itunes:keywords";s:17:"##WordPressCats##";s:13:"itunes:author";s:10:"##Global##";s:15:"itunes:explicit";s:2:"No";s:12:"itunes:block";s:2:"No";}
tags: 
- Society
type: post
status: publish
---
I've been reading "<a href="http://www.amazon.com/Trap-Selling-Afloat-Winner-Take-All-America/dp/0805080651/">The Trap: Selling Out to Stay Afloat in Winner-Take-All America</a>" during the last few evenings and it got me thinking a bit.

One of the basic arguments of the book is that intelligent and educated people are selling out to survive in America. They are forced to make the Devil's choice between living their dreams or having a middle class life.

During the 1980s, people were seen as selling out in order to get rich but the author, Daniel Brooke, makes the argument (personally and through interviews with others) that the truth of the matter, especially 20 years later, is that people are selling out in order to <em>not be poor</em>. In other words, in order to live the kind of life that people in the 1950s and 1960s took as something that could reasonably be had, such as owning your own home, living in the area where you grew up, or sending your kids to a reasonable school, people have to choose to work in those fields that provide an inordinate degree of wealth, regardless of the desirability of those careers. How many people <em>really</em> want to be a corporate lawyer as their dream job? The trade off for making this choice is that service oriented jobs, like teaching or working for a non-profit, or creative jobs, like writing or other artistic careers, are not an option if you want to do well financially and have a family. Brook makes the point that in earlier decades, the starting wage for most professional careers was higher than the cost of a year's tuition at leading universities and that the pay difference between, say, a starting lawyer on Wall Street and a public school teacher was only a couple of thousand dollars a year. Education was affordable, one didn't start a career $80,000 in debt, and taking a professional job was not the choice between money or fulfillment.

These days, in order to own a home in any major city, especially on the coasts, it takes two people working high paying professional careers. Working class people need not apply. My wife and I have certainly found that out. We actually own our home on the Oakland/Berkeley border. We only managed to purchase it because we had the down payment from our previous home, paid for through luck more than planning. That home had grown in value during the boom . Our mortgage is so high that I see little possibility that people with average professional careers could afford a home (we both work in high tech). On top of this, realistically, we bought a lower end home for the Bay Area by buying in Oakland. We couldn't even afford a large house if we'd wanted one. If our house was two miles to the north, well into Berkeley, it would cost at least 50% more. If it was actually in San Francisco, it would be at least double the price we purchased it for. I have friends who are in high paying careers that own one side of a duplex with another couple in San Francisco because that was the only way to have a house. Compare this to the union factory worker or music teacher 40 years ago who was able to buy a home with a normal salary. As an example, both of R's parents were schoolteachers. The pair of them were able to buy a home decades ago (the mid-1960's, I believe) on their pay. This is a a large home right in the middle of Berkeley, perched on a hill with a huge lot. Teachers were able to buy this...

America has effectively priced much of the middle class and all of the working class out of buying homes in most cities. This is one of the roots of the current housing crisis where people are finding that they have mortgages on homes that they cannot really afford to pay now that their homes are no longer going up in value. If you know any professional writers (I know a few) or independent professionals, ask them about the cost of their private health insurance, if they even have any. Ask them about the costs of having children where one half of a working couple needs to quit working for many years (not a cost that can be afforded) or the astronomical cost of child care needs to be assumed somehow.

There was a brief time after World War II where the country was headed the other way. What happened? Well, a lot of things but one of them is that the system of taxation in this country was ripped apart to the advantage of the wealthy. As they say, the rich get richer and the poor get poorer. Housing, for example, is a limited resource in cities. If people want to live in the city, the prices are driven up by supply and demand. If you are wealthy, this is inconvenient and you buy the house (thus continuing to drive the prices up over time). If you are not wealthy, well, I hope you enjoy renting (and sharing your apartment with two or more friends).  At this point, the concentration of wealth and the economic disparity between classes is at the kind of level one expects to see in the so-called "Third World," not the nation that we pretend the United States to be.

But, back to the book, the point is clearly made that most of us that have a choice (this leaves out those that don't even get that far economically) have to choose between the potential of living a fulfilling and creative life in a profession we love and in a place we love or in doing what it takes to make the money to get the life we've been led to expect (home ownership, providing for a family, etc.). While I enjoy much of the work that I do in tech, this point gets driven home every time I think about actually going for that doctorate in Religious Studies or Buddhist Studies. I could do it but could I keep my home and do it? Could I pay to live while I did it? (Heck, could I pay for my child support or my daughter's college?) When I was done with the degree, could I survive working in a field with that degree or would I again have to choose a career in something else because even if jobs are available, the money in them isn't enough to provide a decent livelihood?

How is this going to end? How bad will this get before something is done? I certainly don't expect our bought and sold elected officials in either state or federal governments to do anything about this. They know where their money comes from and they manage to stay in that upper class of society, generally. Sooner or later, something has to give and I really am afraid of what it will look like when this occurs and what it will bring.

To quote the book:
<blockquote>"Those at the bottom are stuck; those with the education needed to get ahead are trapped: do what you need to do to support a family at the ever-rising going rate or do what you want to do and give up on the American Dream. For young educated Americans, the nation is fast becoming the land of compulsory yuppiedom. [...] Today, just paying the bills in metropolitan America requires that most educated young people join up with one of those undertaxed corporations like Cisco or Microsoft or the law, banking, and consulting firms that keep them undertaxed. The best that you can hope for is to become what novelist Douglas Coupland termed a Microserf."</blockquote>
