--- 
wordpress_id: 1551
layout: post
title: The Beard Made Him Do It!
date: 2007-02-21 21:55:09
wordpress_url: http://www.arcanology.com/?p=1551
---
<img hspace="10" src="http://newsimg.bbc.co.uk/media/images/42589000/jpg/_42589511_priest_203_body.jpg" _fcksavedurl="http://newsimg.bbc.co.uk/media/images/42589000/jpg/_42589511_priest_203_body.jpg" align="right" />I guess that I found out what John Michael Greer has been up to lately. (That is humor for the inept...but they have the same beard!) <h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://news.bbc.co.uk/1/hi/world/europe/6376211.stm" _fcksavedurl="http://news.bbc.co.uk/1/hi/world/europe/6376211.stm">Priest jailed for exorcism death</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>A Romanian priest has been jailed for 14 years for conducting an exorcism that led to the death of a nun who he believed was possessed by devils. </strong> Irina Cornici, 23, died after being starved and chained to a cross at a secluded convent in the north-east. The ritual in 2005 was led by Daniel Petru Corogeanu, 31, the priest at the Holy Trinity convent in Tanacu village. He and four nuns were convicted of manslaughter. The nuns got jail terms ranging from five to eight years. Nicoleta Arcalianu got eight years, while Adina Cepraga, Elena Otel and Simona Bardana were given five-year sentences. All the defendants plan to appeal against the verdict in a case which has shocked Romania. The Orthodox Church, which described the Tanacu incident as "abominable", has promised reforms, including psychological tests for those seeking to enter monasteries. It banned Corogeanu from the priesthood and excommunicated the four nuns. In 1999, when the Vatican issued its first new guidelines since 1614 for driving out devils, it urged priests to take modern psychiatry into account in deciding who should be exorcised. After hearing the sentence, Corogeanu said: "We will appeal and hope that it will succeed. We didn't expect this sentence, but this is the judge's decision. We will pray to God for help." Dozens of Corogeanu's supporters packed the courtroom and several burst into tears when the verdict was announced, AP news agency reported. <a href="http://www.warrenellis.com/?p=3795" _fcksavedurl="http://www.warrenellis.com/?p=3795">Comments by Warren Ellis available as well...</a>