--- 
wordpress_id: 1699
layout: post
title: Linus Torvalds on the Whole Microsoft Patent Thing
date: 2007-05-15 11:55:17
wordpress_url: http://www.arcanology.com/?p=1699
---
Information Week has a response from Linus Torvalds, the evil Linux despot, on the whole Microsoft Patent issue from the last few days. You can read the entire bit <a href="http://www.informationweek.com/windows/showArticle.jhtml?articleID=199600443">there</a> but I have an excerpt below: <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "So the whole, 'We have a list and we're not telling you,' itself should tell you something," he said of Microsoft's stance in the Fortune story. And for good measure, he adds: "Don't you think that if Microsoft actually had some really fool-proof patent, they'd just tell us and go, 'nyaah, nyaah, nyaah!'"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </blockquote>