--- 
wordpress_id: 1652
layout: post
title: Jack's Hope
date: 2007-04-03 21:44:25
wordpress_url: http://www.arcanology.com/?p=1652
---
I am Jack's lack of hope for the future... From <a href="http://today.reuters.co.uk/news/articlenews.aspx?type=entertainmentNews&storyid=2007-04-03T230707Z_01_KUA381899_RTRUKOC_0_UK-RICHARDS.xml">Reuters</a>: <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <strong><span class="artTitle">Keith Richards "snorted father's ashes"</span></strong> <span class="newsDate">Tue Apr 3, 2007 11:07 PM BST</span> LONDON (Reuters) - Rolling Stones guitarist Keith Richards said in an interview that he snorted his father's ashes during a drugs binge, British media reported late on Tuesday. The Sun tabloid said the interview appeared in the latest edition of the NME music magazine. An NME spokeswoman said the story was genuine and not a late April Fool's joke, and that the edition in question would appear on newsstands across the country from Wednesday. She did not have a copy of the interview available late on Tuesday. "The strangest thing I've tried to snort?" the Sun quoted Richards as saying in its early Wednesday edition. "My father. I snorted my father. "He was cremated and I couldn't resist grinding him up with a little bit of blow. My dad wouldn't have cared. "It went down pretty well and I'm still alive." According to the report, Richards' father, Bert, died in 2002 aged 84. The 63-year-old rocker, who underwent an operation in New Zealand last year after reportedly falling out of a tree when in Fiji, also took a swipe at some of the big musical acts of today. "Everyone's a load of crap," he said. "They are trying to be somebody else and they ain't being themselves. Libertines, Arctic Monkeys, Bloc Party? Load of crap, load of crap. Posers, rubbish." Richards said he was proud of his ability to survive despite a legendary rock'n'roll lifestyle. "I was number one on the 'Who's Likely To Die' list for 10 years. I mean, I was really disappointed when I fell off the list. "Some doctor told me I had six months to live and I went to their funeral." Richards' publicist in London was not immediately available for comment on the interview.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </blockquote>