--- 
wordpress_id: 1774
layout: post
title: Singularity Summit
date: 2007-08-14 11:59:59
wordpress_url: http://www.arcanology.com/?p=1774
---
I'll be attending the 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href="http://www.singinst.org/summit2007/">Singularity Summit</a> on September 8 and 9 this year. They have a <a href="http://www.singinst.org/summit2007/press/pressreleases/">press release</a> that they put out yesterday on the event. Here is an excerpt: <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...What are the major challenges to achieving advanced AI? What are the benefits and dangers? How far are we from self-improving AI? How should we prepare for this potentially powerful innovation? These are among the questions that 17 outstanding thinkers will explore and debate at the Singularity Summit, to be held Saturday and Sunday, September 8-9, at the Palace of Fine Arts in San Francisco, California. The summit is organized by the Singularity Institute for Artificial Intelligence, a 501(c)(3) not-for-profit institute in Silicon Valley for the study of safe advanced AI. [...] Tickets can be purchased online for $50 at <a href="http://www.singinst.org/summit2007/tickets/">http://www.singinst.org/summit2007/tickets/</a>.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </blockquote> This looks like a fun event for the geek and AI inclined.Â I'm not sure that I expect my Buddhist or Neopagan friends to attend.