--- 
wordpress_id: 1519
layout: post
title: Photoof Photos
date: 2007-01-13 18:48:46
wordpress_url: http://www.arcanology.com/?p=1519
---
As noted at the <a href="http://laughingsquid.com/laughing-squid-decade-2-photoboof-photos/">Laughing Squid blog</a> today, the pictures from the <a href="http://photoboof.com/">Photoboof</a> at the Laughing Squid: Decade 2 party are <a href="http://photoboof.com/thephotoboof/squid06/">finally up</a>. The Photoboof is a rather ingenious vehicle (in many senses) for getting people to misbehave and have fun. I wish that I'd thought of it first! I've uploaded a few to my <a href="http://www.flickr.com/photos/albill/">Flickr account</a> since R and I, as well as a couple of friends and acquaintances, are in them. I include the one with the two of us below. <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a title="Photo Sharing" href="http://www.flickr.com/photos/albill/356390077/"><img width="328" height="965" border="1" alt="Al and Rebecca in the Photoboof" src="http://farm1.static.flickr.com/159/356390077_8e08b755b8_o.jpg" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>