--- 
wordpress_id: 1548
layout: post
title: God's Neighborhood
date: 2007-02-16 13:13:28
wordpress_url: http://www.arcanology.com/?p=1548
---
My friend, Wendi, is posting old photos that she took back in 80's on Flickr. The following one caught my eye: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="http://www.flickr.com/photos/litlnemo/392049775/"><img src="http://farm1.static.flickr.com/153/392049775_7a61947b2c_d.jpg" border="1" height="334" width="500" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>