--- 
wordpress_id: 1535
layout: post
title: Apocalypse Madonna
date: 2007-01-27 19:59:55
wordpress_url: http://www.arcanology.com/?p=1535
---
An interesting image found by Bruce Sterling while in Italy. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="http://www.flickr.com/photos/albill/371351344/" title="Photo Sharing"><img src="http://farm1.static.flickr.com/181/371351344_084ac1c7fb.jpg" alt="apocalypse madonna" border="1" height="500" width="300" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>