--- 
wordpress_id: 1721
layout: post
title: A Comment on the Democratic Leadership
date: 2007-06-11 14:17:54
wordpress_url: http://www.arcanology.com/?p=1721
---
I can't say that I disagree with this but, of course, I never actually believed that the Democrats actually would have the will to make a difference. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <lj-embed></lj-embed>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>