--- 
wordpress_id: 1724
layout: post
title: Ex Templo Podcast #4 Rev. Jiun Foster - Part 3
date: 2007-06-13 10:38:51
wordpress_url: http://www.arcanology.com/?p=1724
---
The fourth 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="http://www.extemplo.org"><strong>Ex Templo</strong></a> podcast is up. This is the final part of my interview with Rev. Foster. Enjoy! <a href="http://www.extemplo.org/?p=7">http://www.extemplo.org/?p=7</a>