--- 
wordpress_id: 1677
layout: post
title: Bad Poetry
date: 2007-04-25 16:10:12
wordpress_url: http://www.arcanology.com/?p=1677
---
I'm listening to a bunch of classes that Jiun Sensei did for our sangha, Daiun-Ji, over the last two years. Listening to these recordings constantly that have been passed through a low bitrate recorder has moved me to write a haiku dedicated to him and the Dharma: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <em>scratchy, distorted, my abbot's voice constantly, cracks jokes while teaching.</em>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p> I think it is time to listen to some Nick Cave or somesuch for a while now... 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>Update a few hours later:</strong> I have received the following from Jiun Sensei: <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <em>demanding students never happy with sensei where is my damn tea?!</em>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p> That seems to qualify as a retort...