--- 
wordpress_id: 1518
layout: post
title: Colbert and the iPhone
date: 2007-01-12 15:50:34
wordpress_url: http://www.arcanology.com/?p=1518
---
Stephen Colbert is "flaccid with rage" over the iPhone. He does point out what the eventual result of Apple's efforts to create a multi-platform device will be: <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img src="http://www.arcanology.com/images/colbert-iphone.jpg" border="1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p> See the whole thing at 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="http://www.applegazette.com/weird/steven-colbert-flacid-with-rage-over-iphone/">Apple Gazette</a>.