--- 
wordpress_id: 1968
layout: post
title: Tokyo Banana
date: 2007-10-10 14:23:29
wordpress_url: http://www.arcanology.com/2007/10/10/tokyo-banana/
---
I'm now back at work after my trip to Japan for the last couple of weeks. While I was in Tokyo, I was able to experience the joy which is the Tokyo Banana. Think of a twinkie-like spongecake (without a shelf life measured in the lifespan of the planet) with a piece of banana in the center. That is the Tokyo Banana. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style="text-align: center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="http://www.flickr.com/photos/albill/1534566236/" title="Photo Sharing"><img src="http://farm3.static.flickr.com/2365/1534566236_5cbee1d2c7.jpg" alt="Tokyo Banana" height="500" width="456" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p> When R and I were waiting at the airport in Tokyo, we found a vender that sold them. We'd seen them at the train stations but we knew that there had to be a convenient source because R's co-workers at Six Apart always brought them back from Japan. Overcome with joy, we bought several boxes so we could both take them in to work. Now, fortified with a foreign food product, the Mozilla QA team soldiers on!