--- 
wordpress_id: 2483
layout: post
title: Political Satire of the Day
date: 2008-09-20 13:57:13
wordpress_url: http://www.arcanology.com/?p=2483
---
I haven't blogged much this last week as I've been reading and engaging in other activities. I do offer this satire of the moment, which I find rather humorous. I actually don't know who the artist is that drew it. I suspect that my left of center politics are not a deep mystery to anyone who reads my blog. <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a title="Red Palin by albill, on Flickr" href="http://www.flickr.com/photos/albill/2873712416/"><img src="http://farm4.static.flickr.com/3180/2873712416_ab38412119_o.png" alt="Red Palin" width="438" height="700" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p> Thanks to Rubylou for turning me on to the image. See you at the November elections!