--- 
wordpress_id: 2393
layout: post
title: Defcon 16 CD and Event Updates
date: 2008-08-17 12:56:39
wordpress_url: http://www.arcanology.com/?p=2393
---
<p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="http://www.flickr.com/photos/albill/2779097343/" title="dc-16-logo by albill, on Flickr"><img src="http://farm4.static.flickr.com/3176/2779097343_d81bf1f7ef_o.png" width="333" height="167" border="0" alt="dc-16-logo" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p> For anyone that wants to find the Defcon 16 CD of presentations, it is on 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="http://thepiratebay.org/torrent/4347389/DEFCON16_2008.rar">popular bittorrent sites</a> but can also be downloaded <a href="http://www.i-hacked.com/freefiles/defcon16.iso">here</a> as well. Most of the talks are pretty close to what was presented. A number of presenters did update talks at the last minute (and said so) but I haven't seen a central clearing house for finding the updated talks. Google Video has various short videos on Defcon 16 <a href="http://video.google.com/videosearch?q=defcon+16">available</a> and I would expect more to show up over time since presentations from Defcon 15 <a href="http://video.google.com/videosearch?q=defcon+16#q=defcon 15">can be found there</a> as well. I also noticed that <a href="http://ca.youtube.com/user/TechWebTV">TechWebTV</a> has short interviews and bits from Black Hat 2008 online. An <a href="http://ca.youtube.com/watch?v=2lGKzHYBXtQ">interview</a> with the fellows from "Satan is on my Friends List" is one example. <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        On a related note, the <a href="http://events.ccc.de/congress/2008/wiki/Main_Page">25th Chaos Communications Congress</a> has put up its <a href="http://events.ccc.de/congress/2008/">Call for Participation</a> for the event this December finally. The named theme this year is "Nothing to Hide." This event takes place from December 27 through the 30 in Berlin and I expect that I will be going to it still.