--- 
wordpress_id: 2228
layout: post
title: Speed Racer
date: 2008-05-24 23:42:09
wordpress_url: http://www.arcanology.com/?p=2228
---
<p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="http://www.flickr.com/photos/albill/2520618336/" title="Speed Racer by albill, on Flickr"><img border="1" src="http://farm3.static.flickr.com/2257/2520618336_5bb1e4e9be.jpg" width="500" height="213" alt="Speed Racer" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p> R and I went and saw 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <strong><a href="http://www.imdb.com/title/tt0811080/">Speed Racer</a></strong> this evening. We both wanted to see it on the big screen. I've heard mixed reviews of it, with some people find it too cartoonish or just frenetic. For a movie done by the Wachowski brothers based on a cartoon, I'm not sure what they were expecting... I enjoyed it quite a bit and I think R did as well. It has a simple plot but it is probably the most psychedelic movie, from the point of few of colors and motion, that I've seen in quite a while. It is just awesome to behold on a big screen. I enjoyed the look and feel quite a bit and I found it a worthwhile night out to go see it. Too each their own. Going to the theater, I did notice the line around it to see the new Indiana Jones movie but I'm glad that I went and saw this while I had the chance. Of course, now I have the sound of Big Black's song, "<a href="http://www.youtube.com/watch?v=T-vmMburpMw">Racer X</a>," running through my head constantly... The <a href="http://movies.yahoo.com/feature/speedracer.html?showVideo=1">first seven minutes</a> of the movie are available online, with higher resolution versions on the site. <lj-embed></lj-embed>