--- 
layout: post
title: Soto Zen Priests Suing E-sangha
published: true
meta: 
  _edit_last: "1"
  ljID: "3350"
  _podPressPostSpecific: a:6:{s:15:"itunes:subtitle";s:15:"##PostExcerpt##";s:14:"itunes:summary";s:15:"##PostExcerpt##";s:15:"itunes:keywords";s:17:"##WordPressCats##";s:13:"itunes:author";s:10:"##Global##";s:15:"itunes:explicit";s:2:"No";s:12:"itunes:block";s:2:"No";}
tags: 
- Buddhism
- e-sangha
- Spirituality
- Technology
type: post
status: publish
---
This is a long post. Be warned. :-)

I've been wanting to write a blog post about some breaking news in regards to the <a href="http://www.lioncity.net/buddhism/">E-sangha web forum</a>, which bills itself as "a place where Buddhists are able to meet on the internet to discuss all matters relating to Buddhism." They also state (on <a href="http://www.e-sangha.com">e-sangha.com</a>):
<blockquote>E-Sangha’s main objective is to provide those who are interested in learning more about Buddhism a meeting place where participants can learn through discussions, and come to a correct understanding of the various aspects involved in Buddha's teachings. E-Sangha's intent is to keep the tradition alive and flourishing, and to help bring peace, harmony and happiness into everyones lives. One does not need to be a Buddhist to benefit from the teachings, the benefits are available to everyone.

E-Sangha Chat &amp; Forum provides forums for participation in discussions which includes all the main traditions such as Mahayana, Vajrayana, Nichiren, Theravada and Zen. There is also a facility for general Buddhist discussion where members are able to engage in exchanging various aspects of this ancient tradition.</blockquote>
I've posted on the E-sangha web forums a few times here. These have turned out to be very popular with site visitors and they receive a lot of traffic. You can read some background in these posts:
<ul>
	<li><a href="http://www.arcanology.com/2007/01/25/e-sangha-and-control-freaks/">E-sangha and Control Freaks</a></li>
	<li><a href="http://www.arcanology.com/2007/11/05/dharma-trolls-e-sangha-and-open-buddha/">Dharma Trolls, E-sangha, and Open Buddha</a></li>
	<li><a href="http://www.arcanology.com/2007/11/30/more-e-sangha-thought-control/">More E-sangha Thought Control</a></li>
	<li><a href="http://www.arcanology.com/2008/03/17/e-sangha-drama-continues/">E-sangha Drama Continues</a></li>
</ul>
<p align="center"><a href="http://www.flickr.com/photos/albill/2075792071/" title="jundo-banned by albill, on Flickr"><img src="http://farm3.static.flickr.com/2061/2075792071_a6489402b1_o.jpg" width="389" height="321" border="1" alt="jundo-banned" /></a></p>
In the <a href="http://www.arcanology.com/2007/11/30/more-e-sangha-thought-control/">More E-sangha Thought Control</a> post, I mentioned the problems that the Soto Zen priest, Jundo Cohen of <a href="http://www.treeleaf.org/">Treeleaf Zendo</a>, had run into with E-sangha for not fulfilling some of the Buddhist doctrinal beliefs of moderators of the site. (You can see <a href="http://treeleafzen.blogspot.com/">his blog</a> for more about him and his practice, as well.) 

Eventually, Rev. Jundo was reinstated there but there have been more recent problems for Soto Zen practitioners on the site. Basically, per my own understanding, E-sangha doesn't allow Buddhist religious specialists (be they monks, nuns, priests or what-have-you) to identify themselves as such on the site to other members unless E-sangha approves of and researches the ordination of these people. If E-sangha doesn't like your organization (or doesn't consider it to be "Buddhist" enough by the beliefs of the moderators), any identification by a member as being ordained will result in the person being banned. This has happened to teachers that I work with who had to choose whether to leave the site or to quit identifying themselves as clergy and answering questions as such. This rule has led to issues between moderation staff and some Japanese traditions, who do not follow the monastic ordination system commonly used elsewhere, not taking the Vinaya monastic vows but, instead, using vows deriving from the Bodhisattva vows. Very recently, this issue came to a head with the result of Zen priests being booted frm E-sangha and the entire Soto Zen forum being summarily shut down on the site by administrators with no explanations given to members. This goes against the idea that E-sangha is really a forum for all Buddhist practitioners (which I haven't believed in quite a while anyway) and in a very obvious way.

As a result of behavior and actions by moderators and administrators on E-sangha, Rev. Jundo and others are suing E-sangha in court. I asked Rev. Jundo for a public statement about all of this since this is rather big news. I present it unedited below in its entirety. For myself, I am not sure how I feel about suing people in court over these disagreements but I can certainly understand the hard feelings concerning behaviors that I've seen by moderators and administrators on E-sangha. I'm not really in a position to judge whether this is the best approach but I do wish people the best of luck in resolving all of this and, perhaps, E-sangha actually living up to its rhetoric towards being inclusive for all Buddhists.

Here is Rev. Jundo's letter:
<blockquote>Dear Al,

I am sorry for the delay getting you this report I promised on our present legal action against E-Sangha, its owner Mr. Leo Kah Leong, its administrators and several of its moderators. We are presently in the middle preparatory stages, there have been several important and truly surprising developments this past week, and that has prevented me from being able to update you.

Let me say at the outset that it is with a very, very heavy heart that we (we are a committee) feel forced into these extreme measures. It is my belief, as a member of the Soto Zen Buddhist clergy, that there should always be peace in the Sangha, that Buddhists should always be willing to communicate with each other and work out their small differences. Litigation between Buddhists is always, always a tragedy.

However, as you well know, the typical response of the E-Sangha administrators to almost all criticism of their actions and dissent is silencing of the speaker, deletion, banishment and an overall attitude of total uncaring. Repeated friendly inquiries, reasonable complaints and specific requests to the administration by Soto Zen clergy, myself included, and others regarding the treatment of our Soto teachers and teachings at the hands of E-Sangha administrators and moderators have simply been ignored, the complaining parties (not the offending parties) punished with suspensions or barring. It is a quite disturbing situation. Prior to being ordained as a Zen priest, I was for many years an attorney-at-law in the United States who often took on pro bono work involving civil liberties, religious discrimination and free speech. At first, I could not believe that I was witnessing, among fellow Buddhists in E-Sangha, the same types of abusive and hateful situations that I had witnessed in religious discrimination cases I had handled for non-Buddhists in the past. To this day, all our overtures to talk to Leo and Todd Marek, the lead administrator of E-Sangha, have been rebuffed. They hang up the phone on us, they do not respond to polite e-mails. In fact, their only response to complaints by myself and other Soto Zen clergy and practitioners on E-Sangha has been to shut down and lock up the "Soto Zen" forum on E-Sangha, an act so egregious that we are making it a cause of action all its own.

We are now gathering affidavits from dozens and dozens of people, both Zen Buddhist practitioners and others, who have encountered like situations with E-Sangha over the years. (If there are any among your readers, of any Buddhist school, who feel that they have a story to tell, and are willing to contribute an affidavit, please have them contact me at jundotreeleaf[a]gmail.com. Right now, I am centering these legal actions only on the effects to our sect of Soto Zen Buddhism, but I see no reason not to expand it to include Buddhists from other schools who have been likewise aggrieved, and I am pressing the other members of our committee to do so. I think it will help our case to include the voices of others as we seek administrative and civil remedies.) We have also downloaded substantially all of the archives of E-Sangha, and have been able to trace dozens and dozens of offensive actions and statements by the administrators and moderators under color of their official capacity. I do not need to list the nature of those offensive actions, and many of your readers will be familiar with them already. However, some of the worst include administrators and moderators referring again and again to recognized and established teachings of sects --other than their own-- as "not Buddhism" or with other harsh and disparaging words. (We are not including comments in posts by persons other than officials of E-Sangha, and I speak only of comments by officials themselves). We have also been able to recreate many deleted postings and take affidavits on those. Our law firm in Singapore has said that it is necessary to show an impact on Soto Zen Buddhists and other Buddhists actually living in Singapore, so we have been able to take statements from such people to support our administrative filings.

If I cannot get communication going with Leo and the other soon (and it does not look like they will change their attitude to even talk to us), we hope to get this filed in Singapore during the fall. I also have a cousin in the States, also an attorney, who is helping me with a parallel action in Illinois (and perhaps Massachusetts, although that is not likely right now), both states with unusually progressive ideas towards religious discrimination laws. Singapore is the home base of E-Sangha and of its owners, and happens to have some of the world's most aggressive legal protections against religious intolerance. For example, under their “Maintenance of Religious Harmony Act”, we can request an order restraining persons and organizations that have engaged in acts causing feelings of enmity, hatred, ill-will or hostility between different religious groups and sects. There is also a licensing authority for the internet, not unlike the FCC for broadcast stations in America, and E-Sangha's actions can be challenged there. We will also be filing a civil claim for damages against several people personally based upon religious defamation and related causes of action. We feel it is our only option to have our voices heard.

I would love to have this resolved with a few simple reform steps by the administration of E-Sangha. I will write you about those next time. We are really asking for some very minor, and common sense, changes in how they do things. We just want to have our members, clergy and teachings treated with respect, as we treat others the same way. It is, after all, meant as a forum for Buddhists of many shades to converse together and learn from each other. No sect of Buddhism, especially among ancient and well recognized schools of Buddhism with deep roots in Asia and thousands of followers now in Europe and North America ... no sect should be held above or below any other. We should all share and relate to each other as brothers and sisters. Thus, it is terrible when administrators and moderators on E-Sangha of one sect of Buddhism use their positions thereby to degrade the doctrines, practices and clergy of other sects. As a Buddhist teacher with a large Sangha which I lead, this saddens me. ‘E-Sangha’ should be a place of mutual understanding, friendship, fraternal support and scholarly interchange. It is not a place for intolerance, name calling and belittling.

Religious discrimination, defamation and inter-denominational intolerance are odious, no matter the guise through which they appear or the doctrinal pretensions behind which they hide. It makes no difference if the vehicle is the spoken word, a book or broadcast program, or merely a blog or forum on the internet. Intolerance is ugly however and whenever it manifests. Its source must be pointed out and rooted out. While some will engage in discriminatory or intolerant conduct knowingly and intentionally, others will do so merely in the belief that they are maintaining a nebulous ideological or doctrinal “purity”, that they are protecting sacred teachings from feared insult or debasement, that only their own personal interpretations and those of the like minded regarding the “Founder’s words and thoughts” are “True” and “Right”. Such is the case when Sunni divides from Shia over which line of believers shall lead the Islamic faithful. Such is the case when a Protestant Christian preacher denies the very Christianity of a Catholic, or of other Protestants holding differing views of Jesus based on their own reading of the Bible. And such is the case among Buddhist sects when one group proposes that its interpretation of the Buddha’s words is the one true way to understand those words, or when one sect’s members seeks to silence or belittle the clergy and members of other sects with whom the former disagree on points of doctrine, or when the doctrine of the latter sect is marked as “not Buddhism” or as a lesser form of Buddhism.

Such comments and opinions would be odious even if limited to a single sect’s own tracts or webpages directed at that sect’s followers exclusively. But it that much more odious when arising among the administrating and moderating officials of a discussion forum purportedly dedicated to a fair and wide presentation of many schools of Buddhism. It is particularly reprehensible when clergy of a subject school are regularly criticized, corrected, categorized or demeaned by clergy and members of other sects, and especially by those baring official titles and the color of authority for the website, in sections of that website devoted to discussion of all forms of Buddhism in general or to the teachings of the subject sect in particular.

In any event, I promise to keep you and your readers posted on this as developments occur over the coming months. As is the nature of litigation, there are long stretches of preparation and information gathering before anything "happens". So, things move slowly, then in little spurts of sudden activity. Who knows? Maybe we can even work these issues out in peace without need to go this route.

I certainly hope so.

Gassho and Peace to You,
Jundo Cohen</blockquote>
I look forward to comments here and people should feel free to contact Rev. Jundo as he has requested.
