--- 
wordpress_id: 2216
layout: post
title: Happy Birthday, My Mighty Wife!
date: 2008-05-05 18:21:43
wordpress_url: http://www.arcanology.com/?p=2216
---
I want to wish my wife, tolerant and heroic soul that she is, a very happy birthday. As you can imagine, she is a bodhisattva with unlimited and heroic compassion for her grump filled, bookish and nerdish spouse. I've been very fortunate that I seem able to remember this day reliably, for some reason. <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="http://www.flickr.com/photos/albill/2469731598/" title="stamp-us-cinco-de-mayo by albill, on Flickr"><img src="http://farm3.static.flickr.com/2283/2469731598_dc0b1a06dc_o.jpg" width="260" height="347" alt="stamp-us-cinco-de-mayo" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>