--- 
wordpress_id: 2469
layout: post
title: A New Hope, Indeed.
date: 2008-09-11 21:48:54
wordpress_url: http://www.arcanology.com/?p=2469
---
Normally, I wouldn't just repost something from elsewhere with little commentary but this is just too good to miss. Of course, I'm a raging geek so you may disagree. <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="http://www.flickr.com/photos/albill/2849481245/" title="anewhope by albill, on Flickr"><img src="http://farm4.static.flickr.com/3058/2849481245_1005684b1d_o.png" width="450" height="661" alt="anewhope" /></a><br />From <a href="http://www.ironicsans.com/2008/09/in_a_political_campaign_far_far_away.html">ironicsans.com</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>