--- 
wordpress_id: 2494
layout: post
title: Washington Mutual Seized and Sold Off by the Government
date: 2008-09-25 21:40:09
wordpress_url: http://www.arcanology.com/?p=2494
---
There you go, folks. From the <a href="http://www.nytimes.com/2008/09/26/business/26wamu.html">New York Times</a>: <blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Washington Mutual, the giant lender that came to symbolize the excesses of the mortgage boom, was seized by federal regulators on Thursday night, in what is by far the largest bank failure in American history. Regulators simultaneously brokered an emergency sale of virtually all of Washington Mutual, the nation’s largest savings and loan to JPMorgan Chase for $1.9 billion, averting another potentially huge taxpayer bill for the rescue of a failing institution. The move came as lawmakers reached a stalemate over the passage of a $700 billion bailout fund designed to help ailing banks, and removed one of America’s most troubled banks from the financial landscape. Customers of Seattle-based WaMu, with $307 billion in assets, are unlikely to be affected, although shareholders and some bondholders will be wiped out. WaMu account holders are guaranteed by the Federal Deposit Insurance Corporation up to $100,000."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </blockquote> Damn, I'm glad that I moved 75% of my money that was in Wamu to other banks and entities over the last two weeks. I know others were doing similar things which, collectively, probably didn't help but there have been good reasons to be paranoid about Wamu recently given its exposure.