--- 
wordpress_id: 2535
layout: post
title: Actually Emotionally Moved By This Election
date: 2008-11-05 00:03:36
wordpress_url: http://www.arcanology.com/?p=2535
---
<p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="http://www.flickr.com/photos/albill/3003684903/" title="obama holo by albill, on Flickr"><img src="http://farm4.static.flickr.com/3022/3003684903_46be1214d8_o.jpg" width="450" height="368" alt="obama holo" border="1" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p> You know, I can be as cynical as the next guy. It isn't hard in this day and age, especially in our scandal saturated environment of constant media. I was surprised to find, watching the election results this evening, that I was actually emotionally moved, and strongly, when it became clear that Obama will be our president. I really hadn't expected the surge of emotion that I felt with the results. So much for my jaded self. I feel like a long nightmare is over tonight. Tomorrow, I may be cynical again because Obama is, at the end of the day, a politician from one of the two major parties. Even with that, this is the only chance that we had to reverse certain directions in this country and perhaps end our ongoing and permanent state of war in the Middle East. I also believe that Obama, unlike McCain, may do what is necessary to address our country's immediate economic issues. I think, no matter what, we're in for hard times but I think things can be done to alleviate some of the pain associated with it. I was also very surprised to see how many of the typically Republican states that have been heavily contested in the last two elections went to Obama, sometimes easily. It gives me some hope that people away from Liberal bastions like California (or the West Coast in general) may be desiring of change and tired of our current troubles as well. We will see. I am expecting that Obama will appoint a cross-party cabinet full of the right people for the jobs, regardless of politics or history. I think it will make a big difference over the next four (or eight!) years to really address things. Let's enjoy this moment of joy while it lasts and get to work on fixing the problems in America.