--- 
wordpress_id: 2246
layout: post
title: Olympic Protests Continue
date: 2008-06-21 14:01:06
wordpress_url: http://www.arcanology.com/?p=2246
---
<div align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div> As you can see above (or 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="http://www.youtube.com/watch?v=LTLorh-D9mI">here</a>), the Olympic torch route is continuing to have protests. This is footage from Katmandu of the crowds of protesters there. It is shameful to see Nepalese police kicking Buddhist monks (though not surprising in a protest situation). It seems unlikely that the situation leading to the Beijing Olympics is going to calm down at any point. It makes me wonder if we might see incidents at the actual olympic events. I do hope that the Chinese don't go completely overboard in their response to protests but the recent events in Tibet make it seem pretty doubtful that restraint will be shown.