--- 
wordpress_id: 2185
layout: post
title: Die, Flickr, Die.
date: 2008-03-11 22:30:22
wordpress_url: http://www.arcanology.com/2008/03/11/die-flickr-die/
---
I was prepared to write a suitably entertaining (or at least educational) entry about the lecture I attended this evening at the Institute of Buddhist Studies in Berkeley. Unfortunately, in the midst of uploading photos to Flickr, the upload failed. Ever since then, if I try to go to Flickr (or a number of Yahoo sites) from any of the machines on my home network, the connection times out. Strangely, if I connect via a remote proxy that I have set up elsewhere (with a different IP address), Flickr immediately comes up. So, it seems that Yahoo is blocking my IP address or something, probably an automated system marked me as someone doing a denial of service attack by uploading large photos to Flickr (go figure). I've written to Flickr support (though I had to use the proxy to do it as you have to get to their site to write to them on a form), so we'll see what happens. Bastards. Until then, I leave you with 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href="http://techgnosis.com/chunkshow-single.php?chunk=chunkfrom-2008-03-09-1152-0.txt">Erik Davis</a> at Burning Man 2007 speaking on "<a href="http://www.matrixmasters.net/blogs/?p=262">The Imagination and the Environment</a>."