--- 
wordpress_id: 2533
layout: post
title: Magical Health Land
date: 2008-10-27 23:08:22
wordpress_url: http://www.arcanology.com/?p=2533
---
Boring health post! I know that someone out there cares so I thought I'd give a health update. While on Saturday, I was so lethargic and exhausted, I couldn't leave home (and missed a workshop at Noisebridge because of it), Sunday was obviously better with my field trip. Today, I felt mostly normal though a bit tired. This, of course, was in time for the visit with the doctor for the results of my tests where he asks, "How are you feeling today?" He seemed less concerned about my suck weekend than the "Oh, so you feel pretty normal today..." We did get the results of almost all of my tests (a couple where they attempt to culture parasites weren't back yet). Since we'd already done 70% of the work, we agreed to do a full physical while I was there, making the whole thing less a waste of time. My lab tests basically showed diddly squat. I'm not anemic or diabetic, my white blood cell count isn't high, sugars are good, and I show know signs of obvious illness in my system. He did an electrocardiogram and a few other tests to round things out and these all came out normal. Because of the extensive paternal family history of heart problems (my dad technically died of a heart attack though his liver was killing him and most of his male cousins or older relatives have had heart attacks or surgery), we decided that we should keep an eye on things. My blood pressure is on the higher end of normal but my cholesterol isn't bad 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <em>except</em> that my good cholesterol is a lot lower than they'd live. To that end, other than admonishing me to continue to lose weight and exercise, I was put on niacin to help address my good cholesterol. Between Egypt and Burning Man (and probably the vegetarian diet over the last four months), my weight is now down 15 pounds from where it was four months ago. Of course, I'm still 40 pounds too heavy working in a sedentary industry (hello, computers!) and would rather read than work out. I really need to lose another 20 or so pounds in the next four months for me to feel like I'm making progress. It all means that I really do need to get off my ass and do some exercise. On a plus note, I felt well enough today that I walked the mile and change to get dinner and the same back. That's definitely something I couldn't have done a few days ago. I'm also awake at 11:00 PM without feeling a need to pass out. So, enough health stuff to a while unless I get a sudden ER trip. I return you to the scheduled hysteria concerning elections, the Internet, and whether I get into my doctoral program or not.