--- 
wordpress_id: 2204
layout: post
title: Firebird at the Cruicible
date: 2008-04-12 00:26:02
wordpress_url: http://www.arcanology.com/?p=2204
---
<p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="http://www.flickr.com/photos/albill/2406486917/" title="Firebird"><img src="http://farm3.static.flickr.com/2297/2406486917_711c7681c7.jpg" width="462" height="500" alt="Firebird" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p> On Thursday night, R, her mother, and I went to one of the first performances of "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="http://www.thecrucible.org/ballet/index.html">Firebird</a>" at the <a href="http://www.thecrucible.org/">Crucible</a> in Oakland. This show is an interpretation of <a href="http://en.wikipedia.org/wiki/The_Firebird">Stravinsky's Firebird</a> done with a combination of fire performances, aerial work, ballet and break dancing. It also included stunt work with a motorcycle and an impressive Pontiac Firebird. For those that are unaware, the Crucible is a non-profit arts center in Oakland dedicated various fire related and industrial forms of art. It was founded by a number of Burning Man artists in 1999 and offers classing in various kinds of metal casting, welding, fabrication, neon work, and sculpture. If you want to learn to weld, cast sculptures, or make things that shoot flames, they are a place to learn these skills. Every year, in Spring, they do a show focusing on dance and fire. In the Summer, they host a fire arts festival. R and I attended one of their festivals when we lived in our old place, about three blocks away, and attended their dance performance, a retelling of <b>Romeo and Juliet</b>, last year. I thought that the show this year was excellent and was actually better done than the show last year, which I liked as well. We brought R's mother with us this year and she really enjoyed the show as well, so it isn't just for Burning Man freaks going out to the playa. I encourage people interested to go to the links above and get tickets for the show. It is going on this weekend and next (April 16 through 19).