--- 
layout: post
title: The Economics of Gangs and Urban Poor
published: true
meta: 
  ljID: "3125"
  _podPressPostSpecific: a:6:{s:15:"itunes:subtitle";s:15:"##PostExcerpt##";s:14:"itunes:summary";s:15:"##PostExcerpt##";s:15:"itunes:keywords";s:17:"##WordPressCats##";s:13:"itunes:author";s:10:"##Global##";s:15:"itunes:explicit";s:7:"Default";s:12:"itunes:block";s:7:"Default";}
tags: 
- Society
type: post
status: publish
---
<a href="http://www.flickr.com/photos/albill/2192174618/" title="gangcover by albill, on Flickr"><img src="http://farm3.static.flickr.com/2006/2192174618_1184665a2e_o.jpg" width="200" height="307" align="right" border="1" hspace="5" vspace="5" alt="gangcover" /></a>NPR has a story that they broadcasted on Dr. Sudhir Venkatesh this last Saturday for his new book, <b><a href="http://www.amazon.com/Gang-Leader-Day-Sociologist-Streets/dp/1594201501/">Gang Leader for a Day</a></b>. You can <a href="http://www.npr.org/templates/story/story.php?storyId=18003654">listen to it online</a>. Most of it is an interview with Dr. Venkatesh and it is quite interesting to listen to if you have the time.

Dr. Venkatesh discusses his experiences, which are detailed in the book, in developing a relationship with the "Black Kings," a Chicago gang that dealt drugs in some of the projects. I've very much been looking forward to this book coming out for a while now. I read one of Dr. Venkatesh's previous books, "<b><a href="http://www.amazon.com/Off-Books-Underground-Economy-Urban/dp/0674023552">Off the Books: The Underground Economy of the Urban Poor</a></b>". That book documented the largely underground (off the books...) economy in the same area of Chicago that he lived and worked within while studying the Black Kings. I found it to be a pretty sensitive and nuanced book with a lot of insight. Dr. Venkatesh really does care about the lives of these people and gets to know them in a way that almost no academic would ever be interested in doing, even if they were able to do so. 

I'm also reading the book, "<b><a href="http://www.amazon.com/Gangs-New-York-Informal-Underworld/dp/1560252758/">The Gangs of New York: An Informal History of the Underworld</a></b>", right now. This is the 1928 book that detailed the heyday of the New York City gangs in all of their terrible and awesome glory (and inspired the movie of the same name). It will be interesting to see how very different the gangs of today are from those of the previous era, when they had political support as well as a financial basis of a different sort. I expect that there are commonalities as well.

Dr. Steven Levitt did a talk at <a href="http://www.ted.com">TED</a> in 2004, which you can view below or on the <a href="http://www.ted.com/index.php/talks/view/id/29">page for it</a>. This talk covers some of the same research with the Black Kings and wound up in Levitt's book, "<b><a href="http://www.amazon.com/Freakonomics-Revised-Expanded-Economist-Everything/dp/0061234001/">Freakonomics</a></b>", and Dr. Levitt discusses Dr. Venkatesh's experiences and things learned in an interesting manner. The talk focuses on the economics of the gang and their business model but is, in my opinion, woefully brief. I would have loved to have heard much more.

<div align="center"><lj-embed><object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="320" height="285" id="VE_Player" align="middle"><param name="movie" value="http://static.videoegg.com/ted/flash/loader.swf"><PARAM NAME="FlashVars" VALUE="bgColor=FFFFFF&file=http://static.videoegg.com/ted/movies/STEVENLEVITT_high.flv&autoPlay=false&fullscreenURL=http://static.videoegg.com/ted/flash/fullscreen.html&forcePlay=false&logo=&allowFullscreen=true"><param name="quality" value="high"><param name="allowScriptAccess" value="always"><param name="bgcolor" value="#FFFFFF"><param name="scale" value="noscale"><param name="wmode" value="window"><embed src="http://static.videoegg.com/ted/flash/loader.swf" FlashVars="bgColor=FFFFFF&file=http://static.videoegg.com/ted/movies/STEVENLEVITT_high.flv&autoPlay=false&fullscreenURL=http://static.videoegg.com/ted/flash/fullscreen.html&forcePlay=false&logo=&allowFullscreen=true" quality="high" allowScriptAccess="always" bgcolor="#FFFFFF" scale="noscale" wmode="window" width="320" height="285" name="VE_Player" align="middle" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"></object></lj-embed></div>

You can actually read the official publication of much of this research, if you you are interested. It is "<b><a href="http://pricetheory.uchicago.edu/levitt/Papers/LevittVenkateshAnEconomicAnalysis2000.pdf">An Economic Analysis of a Drug-Selling Gang's Finances</a></b>" by Steven Levitt and Sudhir Venkatesh. There is an amazing amount of material in all of this.

I wonder what other potential areas of research there are here but, beyond that, I wonder how people like Sudhir Venkatesh can take this kind of work and influence society in a positive manner with it. He learned things, effectively by both getting lucky and by treating people like actual human beings, that others have not come close to before. If we had more people doing work like this and people paying attention to it, we might begin to address some of the problems that our society is having in real ways. It is obvious that the problems that give rise to, for example, gangs and the drug trade, are not simply going to go away, nor are those of the urban poor. It is hopeful to see people tackling these issues in new ways and actually interacting with people as they lives their lives.
