--- 
wordpress_id: 2193
layout: post
title: What's a Zen Retreat Like?
date: 2008-03-26 00:02:00
wordpress_url: http://www.arcanology.com/2008/03/26/whats-a-zen-monastery-like/
---
Have you ever wondered what a Zen retreat is like, especially here in the West? A documentary, "Bodhidharma's Shoe", was filmed at <a href="http://www.bmzc.org">Bodhi Manda Zen Center</a> in New Mexico. This is available for online viewing in two parts on <a href="http://www.revver.com">Revver.com</a>. I've watched both of the two parts and, while not quick paced (for fairly obvious reasons), it is pretty interesting and relatively well done. I'd recommend it to people interested in Zen and what a retreat would be like. <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <lj-embed></lj-embed><br /><a href="http://revver.com/video/681302/bodhidharmas-shoe-zen-sesshin-at-bodhi-mandala-monastery-part-one/">Link to view Part 1</a><br /><a href="http://media.revver.com/qt;download/681302.mov">Link to download Part 1</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <lj-embed></lj-embed><br /><a href="http://revver.com/video/681419/bodhidharmas-shoe-zen-sesshin-at-bodhi-mandala-monastery-part-two/">Link to view Part 2</a><br /><a hre="http://media.revver.com/qt;download/681419.mov">Link to download Part 2</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p> I'm glad to see these sort of media materials being put online and not simply the normal fare of Youtube. I know a lot of this sort of thing is pretty unfamiliar to people and being able to see things, as opposed to just reading about it, is helpful for a lot of people.