--- 
wordpress_id: 2928
layout: post
title: Raygun Gothic Rocketship!
date: 2009-11-24 09:34:44
wordpress_url: http://www.openbuddha.com/2009/11/24/raygun-gothic-rocketship/
---
When people talk about Burning Man, they are generally obligated to speak about the art that occurs there. People build large, intricate, and amazing art pieces (and tiny, insignificant, and funny pieces as well!) for Burning Man. That said, the reality of Burning Man for a lot of people is less about the art and more about community, a big party, and often being mentally "adjusted" at the event. I've always been amazed at the creativity of some of the work that I've seen in the three times I've been (2001, 2006, 2008) to the playa. I think the 3D Maze that was a three story tall cube that I saw my first year blew my mind the most completely. Recently, a local Oakland crew built a Golden Age streamlined rocketship for Burning Man as a sponsored art project. I've seen a few pictures of it but heard no details and hadn't seen it for myself. As it turns out, a short documentary was produced about it that my wife sent over to me this morning. I just watched it and found it both interesting and moving enough in its display of the work of the artists and of the artists, themselves, that I wanted to share it with my friends. The work to create something collaborative and cool, just because, is such a high point for this kind of art. You can watch it below or <a href="http://vimeo.com/7743222">go to Vimeo</a> to see it in a larger size. <lj-embed><p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="http://vimeo.com/7743222">Blast Off!</a> from <a href="http://vimeo.com/user2392023">Sean Donnelly</a> on <a href="http://vimeo.com">Vimeo</a>.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p></lj-embed>