--- 
wordpress_id: 2832
layout: post
title: Zen Motivational Poster
date: 2009-07-11 18:49:37
wordpress_url: http://www.openbuddha.com/?p=2832
---
I saw this today and laughed and laughed and laughed (almost like I was punch drunk). Obviously I need to sit more. <div align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="http://www.flickr.com/photos/albill/3710957239/" title="zen_motivational_poster"><img src="http://farm4.static.flickr.com/3520/3710957239_77543c1ba5.jpg" width="457" height="500" alt="zen_motivational_poster" /></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div> Courtesy of 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://mojo1000.com/1000cuts/zen-motivational-poster.html">MonkMojo's 1000 Cuts</a>.