--- 
wordpress_id: 2723
layout: post
title: Preparing for Spring Retreat
date: 2009-03-24 10:32:40
wordpress_url: http://www.arcanology.com/?p=2723
---
<div align="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="http://www.flickr.com/photos/albill/3381989807/" title="By the short hairs!"><img src="http://farm4.static.flickr.com/3595/3381989807_9e5beaa5b8.jpg" width="500" height="375" alt="By the short hairs!" /></a><br /><em>Pre-shaving trim</em>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div> I'm preparing for the 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="http://cincinnatizen.org/images/spring-retreat-09.pdf">Four Day Sesshin</a> of the <a href="http://fivemountain.org/">Five Mountain Sangha</a> this week. Rev. Paul Lynch, JDPSN, will be leading the retreat and my primary teacher, Rev. Jiun Foster, will be installed as a Dharma Holder there (I and another Dharma brother will be ordained as well). I have to show up with my head shaved so I had my wife take my hair as far down with the clippers as possible last night. I'll be doing the rest with a razor this evening. Tomorrow morning, I catch my flight for Ohio. We'll be in retreat Thursday through Sunday, which is a relatively short retreat, and I'll be back Sunday night. Even with my recent illness (and mostly complete recovery), I've been looking forward to this retreat. It will be a fairly small group of us in Ohio this time and I will, I expect, begin formal koan study with Rev. Lynch. I approach that with a certain amount of trepidation but I look forward to the experiences of that and of the retreat as a whole. I expect that I'll have a few conversations with some of my closer coworkers when I'm back. They know I'm going out and getting ordained and I've tried to explain that they can still expect the same person as before. It isn't like ordination confirms some "holy" status on any of us. It is just a step in the path and I'll still be the same frail human being, like them, as before. My dedication to the good of all beings is the same but my temper and such will probably not magically disappear either. That's up to me to work through over time as I overcome my own obstacles and obscurations.