--- 
wordpress_id: 3679
layout: post
title: Jundo Cohen's Comments on Genpo, Sexuality, Money, and Zen
date: 2011-04-08 21:51:18
wordpress_url: http://www.openbuddha.com/?p=3679
---
Jundo Cohen of <a href="http://www.treeleaf.org/">Treeleaf Zendo</a> offers his amazing, insightful, and <em>hilarious</em> commentary on Genpo Merzel, sexuality, money, and Zen in a video he posted on April Fool's Day, 2011. I encourage everyone to watch it unless they have no sense of humor. <p style="text-align:center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <em>Extra points for placing Genpo Merzel and Brad Warner in the same...position...in his announcements.</em>